CREATE TABLE cities(
   id          INTEGER  NOT NULL
  ,name        NVARCHAR(17) NOT NULL
  ,slug        NVARCHAR(26)
  ,province_id INTEGER  NOT NULL
);
INSERT INTO cities(id,name,slug,province_id) VALUES (1,N'اسکو',N'اسکو',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (2,N'اهر',N'اهر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (3,N'ایلخچی',N'ایلخچی',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (4,N'آبش احمد',N'آبش-احمد',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (5,N'آذرشهر',N'آذرشهر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (6,N'آقکند',N'آقکند',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (7,N'باسمنج',N'باسمنج',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (8,N'بخشایش',N'بخشایش',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (9,N'بستان آباد',N'بستان-آباد',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (10,N'بناب',N'بناب',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (11,N'بناب جدید',N'بناب-جدید',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (12,N'تبریز',N'تبریز',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (13,N'ترک',N'ترک',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (14,N'ترکمانچای',N'ترکمانچای',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (15,N'تسوج',N'تسوج',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (16,N'تیکمه داش',N'تیکمه-داش',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (17,N'جلفا',N'جلفا',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (18,N'خاروانا',N'خاروانا',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (19,N'خامنه',N'خامنه',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (20,N'خراجو',N'خراجو',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (21,N'خسروشهر',N'خسروشهر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (22,N'خضرلو',N'خضرلو',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (23,N'خمارلو',N'خمارلو',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (24,N'خواجه',N'خواجه',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (25,N'دوزدوزان',N'دوزدوزان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (26,N'زرنق',N'زرنق',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (27,N'زنوز',N'زنوز',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (28,N'سراب',N'سراب',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (29,N'سردرود',N'سردرود',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (30,N'سهند',N'سهند',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (31,N'سیس',N'سیس',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (32,N'سیه رود',N'سیه-رود',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (33,N'شبستر',N'شبستر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (34,N'شربیان',N'شربیان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (35,N'شرفخانه',N'شرفخانه',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (36,N'شندآباد',N'شندآباد',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (37,N'صوفیان',N'صوفیان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (38,N'عجب شیر',N'عجب-شیر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (39,N'قره آغاج',N'قره-آغاج',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (40,N'کشکسرای',N'کشکسرای',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (41,N'کلوانق',N'کلوانق',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (42,N'کلیبر',N'کلیبر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (43,N'کوزه کنان',N'کوزه-کنان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (44,N'گوگان',N'گوگان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (45,N'لیلان',N'لیلان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (46,N'مراغه',N'مراغه',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (47,N'مرند',N'مرند',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (48,N'ملکان',N'ملکان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (49,N'ملک کیان',N'ملک-کیان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (50,N'ممقان',N'ممقان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (51,N'مهربان',N'مهربان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (52,N'میانه',N'میانه',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (53,N'نظرکهریزی',N'نظرکهریزی',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (54,N'هادی شهر',N'هادی-شهر',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (55,N'هرگلان',N'هرگلان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (56,N'هریس',N'هریس',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (57,N'هشترود',N'هشترود',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (58,N'هوراند',N'هوراند',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (59,N'وایقان',N'وایقان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (60,N'ورزقان',N'ورزقان',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (61,N'یامچی',N'یامچی',1);
INSERT INTO cities(id,name,slug,province_id) VALUES (62,N'ارومیه',N'ارومیه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (63,N'اشنویه',N'اشنویه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (64,N'ایواوغلی',N'ایواوغلی',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (65,N'آواجیق',N'آواجیق',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (66,N'باروق',N'باروق',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (67,N'بازرگان',N'بازرگان',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (68,N'بوکان',N'بوکان',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (69,N'پلدشت',N'پلدشت',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (70,N'پیرانشهر',N'پیرانشهر',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (71,N'تازه شهر',N'تازه-شهر',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (72,N'تکاب',N'تکاب',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (73,N'چهاربرج',N'چهاربرج',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (74,N'خوی',N'خوی',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (75,N'دیزج دیز',N'دیزج-دیز',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (76,N'ربط',N'ربط',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (77,N'سردشت',N'آذربایجان-غربی-سردشت',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (78,N'سرو',N'سرو',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (79,N'سلماس',N'سلماس',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (80,N'سیلوانه',N'سیلوانه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (81,N'سیمینه',N'سیمینه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (82,N'سیه چشمه',N'سیه-چشمه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (83,N'شاهین دژ',N'شاهین-دژ',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (84,N'شوط',N'شوط',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (85,N'فیرورق',N'فیرورق',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (86,N'قره ضیاءالدین',N'قره-ضیاءالدین',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (87,N'قطور',N'قطور',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (88,N'قوشچی',N'قوشچی',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (89,N'کشاورز',N'کشاورز',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (90,N'گردکشانه',N'گردکشانه',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (91,N'ماکو',N'ماکو',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (92,N'محمدیار',N'محمدیار',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (93,N'محمودآباد',N'آذربایجان-غربی-محمودآباد',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (94,N'مهاباد',N'آذربایجان-غربی-مهاباد',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (95,N'میاندوآب',N'میاندوآب',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (96,N'میرآباد',N'میرآباد',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (97,N'نالوس',N'نالوس',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (98,N'نقده',N'نقده',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (99,N'نوشین',N'نوشین',2);
INSERT INTO cities(id,name,slug,province_id) VALUES (100,N'اردبیل',N'اردبیل',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (101,N'اصلاندوز',N'اصلاندوز',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (102,N'آبی بیگلو',N'آبی-بیگلو',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (103,N'بیله سوار',N'بیله-سوار',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (104,N'پارس آباد',N'پارس-آباد',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (105,N'تازه کند',N'تازه-کند',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (106,N'تازه کندانگوت',N'تازه-کندانگوت',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (107,N'جعفرآباد',N'جعفرآباد',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (108,N'خلخال',N'خلخال',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (109,N'رضی',N'رضی',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (110,N'سرعین',N'سرعین',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (111,N'عنبران',N'عنبران',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (112,N'فخرآباد',N'فخرآباد',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (113,N'کلور',N'کلور',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (114,N'کوراییم',N'کوراییم',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (115,N'گرمی',N'گرمی',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (116,N'گیوی',N'گیوی',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (117,N'لاهرود',N'لاهرود',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (118,N'مشگین شهر',N'مشگین-شهر',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (119,N'نمین',N'نمین',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (120,N'نیر',N'اردبیل-نیر',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (121,N'هشتجین',N'هشتجین',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (122,N'هیر',N'هیر',3);
INSERT INTO cities(id,name,slug,province_id) VALUES (123,N'ابریشم',N'ابریشم',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (124,N'ابوزیدآباد',N'ابوزیدآباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (125,N'اردستان',N'اردستان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (126,N'اژیه',N'اژیه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (127,N'اصفهان',N'اصفهان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (128,N'افوس',N'افوس',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (129,N'انارک',N'انارک',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (130,N'ایمانشهر',N'ایمانشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (131,N'آران وبیدگل',N'آران-وبیدگل',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (132,N'بادرود',N'بادرود',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (133,N'باغ بهادران',N'باغ-بهادران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (134,N'بافران',N'بافران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (135,N'برزک',N'برزک',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (136,N'برف انبار',N'برف-انبار',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (137,N'بهاران شهر',N'بهاران-شهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (138,N'بهارستان',N'بهارستان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (139,N'بوئین و میاندشت',N'بوئین-میاندشت',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (140,N'پیربکران',N'پیربکران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (141,N'تودشک',N'تودشک',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (142,N'تیران',N'تیران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (143,N'جندق',N'جندق',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (144,N'جوزدان',N'جوزدان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (145,N'جوشقان و کامو',N'جوشقان-کامو',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (146,N'چادگان',N'چادگان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (147,N'چرمهین',N'چرمهین',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (148,N'چمگردان',N'چمگردان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (149,N'حبیب آباد',N'حبیب-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (150,N'حسن آباد',N'اصفهان-حسن-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (151,N'حنا',N'حنا',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (152,N'خالدآباد',N'خالدآباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (153,N'خمینی شهر',N'خمینی-شهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (154,N'خوانسار',N'خوانسار',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (155,N'خور',N'اصفهان-خور',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (157,N'خورزوق',N'خورزوق',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (158,N'داران',N'داران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (159,N'دامنه',N'دامنه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (160,N'درچه',N'درچه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (161,N'دستگرد',N'دستگرد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (162,N'دهاقان',N'دهاقان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (163,N'دهق',N'دهق',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (164,N'دولت آباد',N'اصفهان-دولت-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (165,N'دیزیچه',N'دیزیچه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (166,N'رزوه',N'رزوه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (167,N'رضوانشهر',N'اصفهان-رضوانشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (168,N'زاینده رود',N'زاینده-رود',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (169,N'زرین شهر',N'زرین-شهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (170,N'زواره',N'زواره',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (171,N'زیباشهر',N'زیباشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (172,N'سده لنجان',N'سده-لنجان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (173,N'سفیدشهر',N'سفیدشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (174,N'سگزی',N'سگزی',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (175,N'سمیرم',N'سمیرم',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (176,N'شاهین شهر',N'شاهین-شهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (177,N'شهرضا',N'شهرضا',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (178,N'طالخونچه',N'طالخونچه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (179,N'عسگران',N'عسگران',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (180,N'علویجه',N'علویجه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (181,N'فرخی',N'فرخی',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (182,N'فریدونشهر',N'فریدونشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (183,N'فلاورجان',N'فلاورجان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (184,N'فولادشهر',N'فولادشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (185,N'قمصر',N'قمصر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (186,N'قهجاورستان',N'قهجاورستان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (187,N'قهدریجان',N'قهدریجان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (188,N'کاشان',N'کاشان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (189,N'کرکوند',N'کرکوند',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (190,N'کلیشاد و سودرجان',N'کلیشاد-سودرجان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (191,N'کمشچه',N'کمشچه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (192,N'کمه',N'کمه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (193,N'کهریزسنگ',N'کهریزسنگ',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (194,N'کوشک',N'کوشک',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (195,N'کوهپایه',N'کوهپایه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (196,N'گرگاب',N'گرگاب',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (197,N'گزبرخوار',N'گزبرخوار',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (198,N'گلپایگان',N'گلپایگان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (199,N'گلدشت',N'گلدشت',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (200,N'گلشهر',N'گلشهر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (201,N'گوگد',N'گوگد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (202,N'لای بید',N'لای-بید',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (203,N'مبارکه',N'مبارکه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (204,N'مجلسی',N'مجلسی',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (205,N'محمدآباد',N'اصفهان-محمدآباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (206,N'مشکات',N'مشکات',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (207,N'منظریه',N'منظریه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (208,N'مهاباد',N'اصفهان-مهاباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (209,N'میمه',N'اصفهان-میمه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (210,N'نائین',N'نائین',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (211,N'نجف آباد',N'نجف-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (212,N'نصرآباد',N'اصفهان-نصرآباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (213,N'نطنز',N'نطنز',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (214,N'نوش آباد',N'نوش-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (215,N'نیاسر',N'نیاسر',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (216,N'نیک آباد',N'نیک-آباد',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (217,N'هرند',N'هرند',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (218,N'ورزنه',N'ورزنه',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (219,N'ورنامخواست',N'ورنامخواست',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (220,N'وزوان',N'وزوان',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (221,N'ونک',N'ونک',4);
INSERT INTO cities(id,name,slug,province_id) VALUES (222,N'اسارا',N'اسارا',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (223,N'اشتهارد',N'اشتهارد',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (224,N'تنکمان',N'تنکمان',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (225,N'چهارباغ',N'چهارباغ',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (226,N'سعید آباد',N'سعید-آباد',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (227,N'شهر جدید هشتگرد',N'شهر-جدید-هشتگرد',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (228,N'طالقان',N'طالقان',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (229,N'کرج',N'کرج',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (230,N'کمال شهر',N'کمال-شهر',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (231,N'کوهسار',N'کوهسار',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (232,N'گرمدره',N'گرمدره',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (233,N'ماهدشت',N'ماهدشت',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (234,N'محمدشهر',N'البرز-محمدشهر',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (235,N'مشکین دشت',N'مشکین-دشت',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (236,N'نظرآباد',N'نظرآباد',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (237,N'هشتگرد',N'هشتگرد',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (238,N'ارکواز',N'ارکواز',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (239,N'ایلام',N'ایلام',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (240,N'ایوان',N'ایوان',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (241,N'آبدانان',N'آبدانان',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (242,N'آسمان آباد',N'آسمان-آباد',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (243,N'بدره',N'بدره',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (244,N'پهله',N'پهله',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (245,N'توحید',N'توحید',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (246,N'چوار',N'چوار',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (247,N'دره شهر',N'دره-شهر',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (248,N'دلگشا',N'دلگشا',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (249,N'دهلران',N'دهلران',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (250,N'زرنه',N'زرنه',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (251,N'سراب باغ',N'سراب-باغ',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (252,N'سرابله',N'سرابله',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (253,N'صالح آباد',N'ایلام-صالح-آباد',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (254,N'لومار',N'لومار',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (255,N'مهران',N'مهران',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (256,N'مورموری',N'مورموری',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (257,N'موسیان',N'موسیان',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (258,N'میمه',N'ایلام-میمه',6);
INSERT INTO cities(id,name,slug,province_id) VALUES (259,N'امام حسن',N'امام-حسن',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (260,N'انارستان',N'انارستان',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (261,N'اهرم',N'اهرم',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (262,N'آب پخش',N'آب-پخش',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (263,N'آبدان',N'آبدان',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (264,N'برازجان',N'برازجان',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (265,N'بردخون',N'بردخون',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (266,N'بندردیر',N'بندردیر',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (267,N'بندردیلم',N'بندردیلم',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (268,N'بندرریگ',N'بندرریگ',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (269,N'بندرکنگان',N'بندرکنگان',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (270,N'بندرگناوه',N'بندرگناوه',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (271,N'بنک',N'بنک',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (272,N'بوشهر',N'بوشهر',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (273,N'تنگ ارم',N'تنگ-ارم',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (274,N'جم',N'جم',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (275,N'چغادک',N'چغادک',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (276,N'خارک',N'خارک',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (277,N'خورموج',N'خورموج',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (278,N'دالکی',N'دالکی',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (279,N'دلوار',N'دلوار',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (280,N'ریز',N'ریز',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (281,N'سعدآباد',N'سعدآباد',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (282,N'سیراف',N'سیراف',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (283,N'شبانکاره',N'شبانکاره',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (284,N'شنبه',N'شنبه',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (285,N'عسلویه',N'عسلویه',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (286,N'کاکی',N'کاکی',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (287,N'کلمه',N'کلمه',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (288,N'نخل تقی',N'نخل-تقی',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (289,N'وحدتیه',N'وحدتیه',7);
INSERT INTO cities(id,name,slug,province_id) VALUES (290,N'ارجمند',N'ارجمند',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (291,N'اسلامشهر',N'اسلامشهر',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (292,N'اندیشه',N'اندیشه',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (293,N'آبسرد',N'آبسرد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (294,N'آبعلی',N'آبعلی',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (295,N'باغستان',N'باغستان',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (296,N'باقرشهر',N'باقرشهر',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (297,N'بومهن',N'بومهن',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (298,N'پاکدشت',N'پاکدشت',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (299,N'پردیس',N'پردیس',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (300,N'پیشوا',N'پیشوا',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (301,N'تهران',N'تهران',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (302,N'جوادآباد',N'جوادآباد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (303,N'چهاردانگه',N'چهاردانگه',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (304,N'حسن آباد',N'تهران-حسن-آباد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (305,N'دماوند',N'دماوند',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (306,N'دیزین',N'دیزین',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (307,N'شهر ری',N'شهر-ری',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (308,N'رباط کریم',N'رباط-کریم',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (309,N'رودهن',N'رودهن',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (310,N'شاهدشهر',N'شاهدشهر',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (311,N'شریف آباد',N'شریف-آباد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (312,N'شمشک',N'شمشک',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (313,N'شهریار',N'شهریار',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (314,N'صالح آباد',N'تهران-صالح-آباد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (315,N'صباشهر',N'صباشهر',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (316,N'صفادشت',N'صفادشت',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (317,N'فردوسیه',N'فردوسیه',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (318,N'فشم',N'فشم',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (319,N'فیروزکوه',N'فیروزکوه',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (320,N'قدس',N'قدس',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (321,N'قرچک',N'قرچک',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (322,N'کهریزک',N'کهریزک',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (323,N'کیلان',N'کیلان',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (324,N'گلستان',N'شهر-گلستان',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (325,N'لواسان',N'لواسان',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (326,N'ملارد',N'ملارد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (327,N'میگون',N'میگون',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (328,N'نسیم شهر',N'نسیم-شهر',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (329,N'نصیرآباد',N'نصیرآباد',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (330,N'وحیدیه',N'وحیدیه',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (331,N'ورامین',N'ورامین',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (332,N'اردل',N'اردل',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (333,N'آلونی',N'آلونی',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (334,N'باباحیدر',N'باباحیدر',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (335,N'بروجن',N'بروجن',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (336,N'بلداجی',N'بلداجی',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (337,N'بن',N'بن',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (338,N'جونقان',N'جونقان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (339,N'چلگرد',N'چلگرد',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (340,N'سامان',N'سامان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (341,N'سفیددشت',N'سفیددشت',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (342,N'سودجان',N'سودجان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (343,N'سورشجان',N'سورشجان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (344,N'شلمزار',N'شلمزار',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (345,N'شهرکرد',N'شهرکرد',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (346,N'طاقانک',N'طاقانک',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (347,N'فارسان',N'فارسان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (348,N'فرادنبه',N'فرادبنه',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (349,N'فرخ شهر',N'فرخ-شهر',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (350,N'کیان',N'کیان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (351,N'گندمان',N'گندمان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (352,N'گهرو',N'گهرو',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (353,N'لردگان',N'لردگان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (354,N'مال خلیفه',N'مال-خلیفه',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (355,N'ناغان',N'ناغان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (356,N'نافچ',N'نافچ',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (357,N'نقنه',N'نقنه',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (358,N'هفشجان',N'هفشجان',9);
INSERT INTO cities(id,name,slug,province_id) VALUES (359,N'ارسک',N'ارسک',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (360,N'اسدیه',N'اسدیه',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (361,N'اسفدن',N'اسفدن',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (362,N'اسلامیه',N'اسلامیه',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (363,N'آرین شهر',N'آرین-شهر',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (364,N'آیسک',N'آیسک',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (365,N'بشرویه',N'بشرویه',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (366,N'بیرجند',N'بیرجند',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (367,N'حاجی آباد',N'خراسان-جنوبی-حاجی-آباد',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (368,N'خضری دشت بیاض',N'خضری-دشت-بیاض',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (369,N'خوسف',N'خوسف',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (370,N'زهان',N'زهان',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (371,N'سرایان',N'سرایان',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (372,N'سربیشه',N'سربیشه',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (373,N'سه قلعه',N'سه-قلعه',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (374,N'شوسف',N'شوسف',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (375,N'طبس',N'خراسان-جنوبی-طبس-',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (376,N'فردوس',N'فردوس',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (377,N'قاین',N'قاین',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (378,N'قهستان',N'قهستان',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (379,N'محمدشهر',N'خراسان-جنوبی-محمدشهر',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (380,N'مود',N'مود',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (381,N'نهبندان',N'نهبندان',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (382,N'نیمبلوک',N'نیمبلوک',10);
INSERT INTO cities(id,name,slug,province_id) VALUES (383,N'احمدآباد صولت',N'احمدآباد-صولت',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (384,N'انابد',N'انابد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (385,N'باجگیران',N'باجگیران',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (386,N'باخرز',N'باخرز',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (387,N'بار',N'بار',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (388,N'بایگ',N'بایگ',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (389,N'بجستان',N'بجستان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (390,N'بردسکن',N'بردسکن',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (391,N'بیدخت',N'بیدخت',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (392,N'تایباد',N'تایباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (393,N'تربت جام',N'تربت-جام',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (394,N'تربت حیدریه',N'تربت-حیدریه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (395,N'جغتای',N'جغتای',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (396,N'جنگل',N'جنگل',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (397,N'چاپشلو',N'چاپشلو',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (398,N'چکنه',N'چکنه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (399,N'چناران',N'چناران',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (400,N'خرو',N'خرو',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (401,N'خلیل آباد',N'خلیل-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (402,N'خواف',N'خواف',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (403,N'داورزن',N'داورزن',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (404,N'درگز',N'درگز',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (405,N'در رود',N'در-رود',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (406,N'دولت آباد',N'خراسان-رضوی-دولت-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (407,N'رباط سنگ',N'رباط-سنگ',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (408,N'رشتخوار',N'رشتخوار',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (409,N'رضویه',N'رضویه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (410,N'روداب',N'روداب',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (411,N'ریوش',N'ریوش',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (412,N'سبزوار',N'سبزوار',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (413,N'سرخس',N'سرخس',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (414,N'سفیدسنگ',N'سفیدسنگ',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (415,N'سلامی',N'سلامی',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (416,N'سلطان آباد',N'سلطان-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (417,N'سنگان',N'سنگان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (418,N'شادمهر',N'شادمهر',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (419,N'شاندیز',N'شاندیز',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (420,N'ششتمد',N'ششتمد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (421,N'شهرآباد',N'شهرآباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (422,N'شهرزو',N'شهرزو',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (423,N'صالح آباد',N'خراسان-رضوی-صالح-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (424,N'طرقبه',N'طرقبه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (425,N'عشق آباد',N'خراسان-رضوی-عشق-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (426,N'فرهادگرد',N'فرهادگرد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (427,N'فریمان',N'فریمان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (428,N'فیروزه',N'فیروزه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (429,N'فیض آباد',N'فیض-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (430,N'قاسم آباد',N'قاسم-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (431,N'قدمگاه',N'قدمگاه',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (432,N'قلندرآباد',N'قلندرآباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (433,N'قوچان',N'قوچان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (434,N'کاخک',N'کاخک',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (435,N'کاریز',N'کاریز',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (436,N'کاشمر',N'کاشمر',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (437,N'کدکن',N'کدکن',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (438,N'کلات',N'کلات',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (439,N'کندر',N'کندر',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (440,N'گلمکان',N'گلمکان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (441,N'گناباد',N'گناباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (442,N'لطف آباد',N'لطف-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (443,N'مزدآوند',N'مزدآوند',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (444,N'مشهد',N'مشهد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (445,N'ملک آباد',N'ملک-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (446,N'نشتیفان',N'نشتیفان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (447,N'نصرآباد',N'خراسان-رضوی-نصرآباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (448,N'نقاب',N'نقاب',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (449,N'نوخندان',N'نوخندان',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (450,N'نیشابور',N'نیشابور',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (451,N'نیل شهر',N'نیل-شهر',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (452,N'همت آباد',N'همت-آباد',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (453,N'یونسی',N'یونسی',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (454,N'اسفراین',N'اسفراین',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (455,N'ایور',N'ایور',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (456,N'آشخانه',N'آشخانه',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (457,N'بجنورد',N'بجنورد',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (458,N'پیش قلعه',N'پیش-قلعه',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (459,N'تیتکانلو',N'تیتکانلو',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (460,N'جاجرم',N'جاجرم',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (461,N'حصارگرمخان',N'حصارگرمخان',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (462,N'درق',N'درق',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (463,N'راز',N'راز',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (464,N'سنخواست',N'سنخواست',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (465,N'شوقان',N'شوقان',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (466,N'شیروان',N'شیروان',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (467,N'صفی آباد',N'خراسان-شمالی-صفی-آباد',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (468,N'فاروج',N'فاروج',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (469,N'قاضی',N'قاضی',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (470,N'گرمه',N'گرمه',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (471,N'لوجلی',N'لوجلی',12);
INSERT INTO cities(id,name,slug,province_id) VALUES (472,N'اروندکنار',N'اروندکنار',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (473,N'الوان',N'الوان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (474,N'امیدیه',N'امیدیه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (475,N'اندیمشک',N'اندیمشک',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (476,N'اهواز',N'اهواز',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (477,N'ایذه',N'ایذه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (478,N'آبادان',N'آبادان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (479,N'آغاجاری',N'آغاجاری',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (480,N'باغ ملک',N'باغ-ملک',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (481,N'بستان',N'بستان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (482,N'بندرامام خمینی',N'بندرامام-خمینی',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (483,N'بندرماهشهر',N'بندرماهشهر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (484,N'بهبهان',N'بهبهان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (485,N'ترکالکی',N'ترکالکی',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (486,N'جایزان',N'جایزان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (487,N'چمران',N'چمران',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (488,N'چویبده',N'چویبده',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (489,N'حر',N'حر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (490,N'حسینیه',N'حسینیه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (491,N'حمزه',N'حمزه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (492,N'حمیدیه',N'حمیدیه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (493,N'خرمشهر',N'خرمشهر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (494,N'دارخوین',N'دارخوین',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (495,N'دزآب',N'دزآب',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (496,N'دزفول',N'دزفول',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (497,N'دهدز',N'دهدز',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (498,N'رامشیر',N'رامشیر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (499,N'رامهرمز',N'رامهرمز',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (500,N'رفیع',N'رفیع',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (501,N'زهره',N'زهره',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (502,N'سالند',N'سالند',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (503,N'سردشت',N'خوزستان-سردشت',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (504,N'سوسنگرد',N'سوسنگرد',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (505,N'شادگان',N'شادگان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (506,N'شاوور',N'شاوور',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (507,N'شرافت',N'شرافت',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (508,N'شوش',N'شوش',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (509,N'شوشتر',N'شوشتر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (510,N'شیبان',N'شیبان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (511,N'صالح شهر',N'صالح-شهر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (512,N'صفی آباد',N'خوزستان-صفی-آباد',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (513,N'صیدون',N'صیدون',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (514,N'قلعه تل',N'قلعه-تل',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (515,N'قلعه خواجه',N'قلعه-خواجه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (516,N'گتوند',N'گتوند',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (517,N'لالی',N'لالی',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (518,N'مسجدسلیمان',N'مسجدسلیمان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (520,N'ملاثانی',N'ملاثانی',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (521,N'میانرود',N'میانرود',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (522,N'مینوشهر',N'مینوشهر',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (523,N'هفتگل',N'هفتگل',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (524,N'هندیجان',N'هندیجان',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (525,N'هویزه',N'هویزه',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (526,N'ویس',N'ویس',13);
INSERT INTO cities(id,name,slug,province_id) VALUES (527,N'ابهر',N'ابهر',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (528,N'ارمغان خانه',N'ارمغان-خانه',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (529,N'آب بر',N'آب-بر',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (530,N'چورزق',N'چورزق',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (531,N'حلب',N'حلب',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (532,N'خرمدره',N'خرمدره',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (533,N'دندی',N'دندی',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (534,N'زرین آباد',N'زرین-آباد',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (535,N'زرین رود',N'زرین-رود',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (536,N'زنجان',N'زنجان',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (537,N'سجاس',N'سجاس',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (538,N'سلطانیه',N'سلطانیه',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (539,N'سهرورد',N'سهرورد',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (540,N'صائین قلعه',N'صائین-قلعه',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (541,N'قیدار',N'قیدار',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (542,N'گرماب',N'گرماب',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (543,N'ماه نشان',N'ماه-نشان',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (544,N'هیدج',N'هیدج',14);
INSERT INTO cities(id,name,slug,province_id) VALUES (545,N'امیریه',N'امیریه',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (546,N'ایوانکی',N'ایوانکی',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (547,N'آرادان',N'آرادان',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (548,N'بسطام',N'بسطام',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (549,N'بیارجمند',N'بیارجمند',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (550,N'دامغان',N'دامغان',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (551,N'درجزین',N'درجزین',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (552,N'دیباج',N'دیباج',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (553,N'سرخه',N'سرخه',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (554,N'سمنان',N'سمنان',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (555,N'شاهرود',N'شاهرود',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (556,N'شهمیرزاد',N'شهمیرزاد',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (557,N'کلاته خیج',N'کلاته-خیج',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (558,N'گرمسار',N'گرمسار',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (559,N'مجن',N'مجن',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (560,N'مهدی شهر',N'مهدی-شهر',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (561,N'میامی',N'میامی',15);
INSERT INTO cities(id,name,slug,province_id) VALUES (562,N'ادیمی',N'ادیمی',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (563,N'اسپکه',N'اسپکه',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (564,N'ایرانشهر',N'ایرانشهر',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (565,N'بزمان',N'بزمان',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (566,N'بمپور',N'بمپور',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (567,N'بنت',N'بنت',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (568,N'بنجار',N'بنجار',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (569,N'پیشین',N'پیشین',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (570,N'جالق',N'جالق',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (571,N'چابهار',N'چابهار',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (572,N'خاش',N'خاش',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (573,N'دوست محمد',N'دوست-محمد',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (574,N'راسک',N'راسک',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (575,N'زابل',N'زابل',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (576,N'زابلی',N'زابلی',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (577,N'زاهدان',N'زاهدان',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (578,N'زهک',N'زهک',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (579,N'سراوان',N'سراوان',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (580,N'سرباز',N'سرباز',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (581,N'سوران',N'سوران',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (582,N'سیرکان',N'سیرکان',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (583,N'علی اکبر',N'علی-اکبر',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (584,N'فنوج',N'فنوج',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (585,N'قصرقند',N'قصرقند',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (586,N'کنارک',N'کنارک',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (587,N'گشت',N'گشت',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (588,N'گلمورتی',N'گلمورتی',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (589,N'محمدان',N'محمدان',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (590,N'محمدآباد',N'سیستان-و-بلوچستان-محمدآباد',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (591,N'محمدی',N'محمدی',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (592,N'میرجاوه',N'میرجاوه',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (593,N'نصرت آباد',N'نصرت-آباد',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (594,N'نگور',N'نگور',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (595,N'نوک آباد',N'نوک-آباد',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (596,N'نیک شهر',N'نیک-شهر',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (597,N'هیدوچ',N'هیدوچ',16);
INSERT INTO cities(id,name,slug,province_id) VALUES (598,N'اردکان',N'فارس-اردکان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (599,N'ارسنجان',N'ارسنجان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (600,N'استهبان',N'استهبان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (601,N'اشکنان',N'اشکنان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (602,N'افزر',N'افزر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (603,N'اقلید',N'اقلید',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (604,N'امام شهر',N'امام-شهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (605,N'اهل',N'اهل',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (606,N'اوز',N'اوز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (607,N'ایج',N'ایج',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (608,N'ایزدخواست',N'ایزدخواست',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (609,N'آباده',N'آباده',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (610,N'آباده طشک',N'آباده-طشک',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (611,N'باب انار',N'باب-انار',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (612,N'بالاده',N'فارس-بالاده',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (613,N'بنارویه',N'بنارویه',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (614,N'بهمن',N'بهمن',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (615,N'بوانات',N'بوانات',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (616,N'بیرم',N'بیرم',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (617,N'بیضا',N'بیضا',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (618,N'جنت شهر',N'جنت-شهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (619,N'جهرم',N'جهرم',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (620,N'جویم',N'جویم',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (621,N'زرین دشت',N'زرین-دشت',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (622,N'حسن آباد',N'فارس-حسن-آباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (623,N'خان زنیان',N'خان-زنیان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (624,N'خاوران',N'خاوران',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (625,N'خرامه',N'خرامه',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (626,N'خشت',N'خشت',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (627,N'خنج',N'خنج',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (628,N'خور',N'فارس-خور',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (629,N'داراب',N'داراب',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (630,N'داریان',N'داریان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (631,N'دبیران',N'دبیران',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (632,N'دژکرد',N'دژکرد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (633,N'دهرم',N'دهرم',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (634,N'دوبرجی',N'دوبرجی',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (635,N'رامجرد',N'رامجرد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (636,N'رونیز',N'رونیز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (637,N'زاهدشهر',N'زاهدشهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (638,N'زرقان',N'زرقان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (639,N'سده',N'سده',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (640,N'سروستان',N'سروستان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (641,N'سعادت شهر',N'سعادت-شهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (642,N'سورمق',N'سورمق',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (643,N'سیدان',N'سیدان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (644,N'ششده',N'ششده',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (645,N'شهرپیر',N'شهرپیر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (646,N'شهرصدرا',N'شهرصدرا',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (647,N'شیراز',N'شیراز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (648,N'صغاد',N'صغاد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (649,N'صفاشهر',N'صفاشهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (650,N'علامرودشت',N'علامرودشت',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (651,N'فدامی',N'فدامی',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (652,N'فراشبند',N'فراشبند',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (653,N'فسا',N'فسا',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (654,N'فیروزآباد',N'فارس-فیروزآباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (655,N'قائمیه',N'قائمیه',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (656,N'قادرآباد',N'قادرآباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (657,N'قطب آباد',N'قطب-آباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (658,N'قطرویه',N'قطرویه',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (659,N'قیر',N'قیر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (660,N'کارزین (فتح آباد)',N'کارزین-فتح-آباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (661,N'کازرون',N'کازرون',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (662,N'کامفیروز',N'کامفیروز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (663,N'کره ای',N'کره-ای',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (664,N'کنارتخته',N'کنارتخته',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (665,N'کوار',N'کوار',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (666,N'گراش',N'گراش',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (667,N'گله دار',N'گله-دار',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (668,N'لار',N'لار',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (669,N'لامرد',N'لامرد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (670,N'لپویی',N'لپویی',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (671,N'لطیفی',N'لطیفی',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (672,N'مبارک آباددیز',N'مبارک-آباددیز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (673,N'مرودشت',N'مرودشت',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (674,N'مشکان',N'مشکان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (675,N'مصیری',N'مصیری',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (676,N'مهر',N'مهر',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (677,N'میمند',N'میمند',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (678,N'نوبندگان',N'نوبندگان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (679,N'نوجین',N'نوجین',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (680,N'نودان',N'نودان',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (681,N'نورآباد',N'فارس-نورآباد',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (682,N'نی ریز',N'نی-ریز',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (683,N'وراوی',N'وراوی',17);
INSERT INTO cities(id,name,slug,province_id) VALUES (684,N'ارداق',N'ارداق',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (685,N'اسفرورین',N'اسفرورین',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (686,N'اقبالیه',N'اقبالیه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (687,N'الوند',N'الوند',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (688,N'آبگرم',N'آبگرم',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (689,N'آبیک',N'آبیک',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (690,N'آوج',N'آوج',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (691,N'بوئین زهرا',N'بوئین-زهرا',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (692,N'بیدستان',N'بیدستان',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (693,N'تاکستان',N'تاکستان',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (694,N'خاکعلی',N'خاکعلی',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (695,N'خرمدشت',N'خرمدشت',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (696,N'دانسفهان',N'دانسفهان',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (697,N'رازمیان',N'رازمیان',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (698,N'سگزآباد',N'سگزآباد',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (699,N'سیردان',N'سیردان',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (700,N'شال',N'شال',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (701,N'شریفیه',N'شریفیه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (702,N'ضیاآباد',N'ضیاآباد',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (703,N'قزوین',N'قزوین',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (704,N'کوهین',N'کوهین',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (705,N'محمدیه',N'محمدیه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (706,N'محمودآباد نمونه',N'محمودآباد-نمونه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (707,N'معلم کلایه',N'معلم-کلایه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (708,N'نرجه',N'نرجه',18);
INSERT INTO cities(id,name,slug,province_id) VALUES (709,N'جعفریه',N'جعفریه',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (710,N'دستجرد',N'دستجرد',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (711,N'سلفچگان',N'سلفچگان',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (712,N'قم',N'قم',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (713,N'قنوات',N'قنوات',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (714,N'کهک',N'کهک',19);
INSERT INTO cities(id,name,slug,province_id) VALUES (715,N'آرمرده',N'آرمرده',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (716,N'بابارشانی',N'بابارشانی',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (717,N'بانه',N'بانه',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (718,N'بلبان آباد',N'بلبان-آباد',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (719,N'بوئین سفلی',N'بوئین-سفلی',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (720,N'بیجار',N'بیجار',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (721,N'چناره',N'چناره',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (722,N'دزج',N'دزج',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (723,N'دلبران',N'دلبران',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (724,N'دهگلان',N'دهگلان',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (725,N'دیواندره',N'دیواندره',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (726,N'زرینه',N'زرینه',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (727,N'سروآباد',N'سروآباد',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (728,N'سریش آباد',N'سریش-آباد',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (729,N'سقز',N'سقز',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (730,N'سنندج',N'سنندج',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (731,N'شویشه',N'شویشه',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (732,N'صاحب',N'صاحب',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (733,N'قروه',N'قروه',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (734,N'کامیاران',N'کامیاران',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (735,N'کانی دینار',N'کانی-دینار',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (736,N'کانی سور',N'کانی-سور',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (737,N'مریوان',N'مریوان',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (738,N'موچش',N'موچش',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (739,N'یاسوکند',N'یاسوکند',20);
INSERT INTO cities(id,name,slug,province_id) VALUES (740,N'اختیارآباد',N'اختیارآباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (741,N'ارزوئیه',N'ارزوئیه',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (742,N'امین شهر',N'امین-شهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (743,N'انار',N'انار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (744,N'اندوهجرد',N'اندوهجرد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (745,N'باغین',N'باغین',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (746,N'بافت',N'بافت',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (747,N'بردسیر',N'بردسیر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (748,N'بروات',N'بروات',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (749,N'بزنجان',N'بزنجان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (750,N'بم',N'بم',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (751,N'بهرمان',N'بهرمان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (752,N'پاریز',N'پاریز',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (753,N'جبالبارز',N'جبالبارز',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (754,N'جوپار',N'جوپار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (755,N'جوزم',N'جوزم',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (756,N'جیرفت',N'جیرفت',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (757,N'چترود',N'چترود',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (758,N'خاتون آباد',N'خاتون-آباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (759,N'خانوک',N'خانوک',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (760,N'خورسند',N'خورسند',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (761,N'درب بهشت',N'درب-بهشت',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (762,N'دهج',N'دهج',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (763,N'رابر',N'رابر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (764,N'راور',N'راور',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (765,N'راین',N'راین',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (766,N'رفسنجان',N'رفسنجان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (767,N'رودبار',N'کرمان-رودبار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (768,N'ریحان شهر',N'ریحان-شهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (769,N'زرند',N'زرند',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (770,N'زنگی آباد',N'زنگی-آباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (771,N'زیدآباد',N'زیدآباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (772,N'سیرجان',N'سیرجان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (773,N'شهداد',N'شهداد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (774,N'شهربابک',N'شهربابک',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (775,N'صفائیه',N'صفائیه',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (776,N'عنبرآباد',N'عنبرآباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (777,N'فاریاب',N'فاریاب',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (778,N'فهرج',N'فهرج',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (779,N'قلعه گنج',N'قلعه-گنج',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (780,N'کاظم آباد',N'کاظم-آباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (781,N'کرمان',N'کرمان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (782,N'کشکوئیه',N'کشکوئیه',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (783,N'کهنوج',N'کهنوج',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (784,N'کوهبنان',N'کوهبنان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (785,N'کیانشهر',N'کیانشهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (786,N'گلباف',N'گلباف',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (787,N'گلزار',N'گلزار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (788,N'لاله زار',N'لاله-زار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (789,N'ماهان',N'ماهان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (790,N'محمدآباد',N'کرمان-محمدآباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (791,N'محی آباد',N'محی-آباد',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (792,N'مردهک',N'مردهک',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (793,N'مس سرچشمه',N'مس-سرچشمه',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (794,N'منوجان',N'منوجان',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (795,N'نجف شهر',N'نجف-شهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (796,N'نرماشیر',N'نرماشیر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (797,N'نظام شهر',N'نظام-شهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (798,N'نگار',N'نگار',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (799,N'نودژ',N'نودژ',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (800,N'هجدک',N'هجدک',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (801,N'یزدان شهر',N'یزدان-شهر',21);
INSERT INTO cities(id,name,slug,province_id) VALUES (802,N'ازگله',N'ازگله',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (803,N'اسلام آباد غرب',N'اسلام-آباد-غرب',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (804,N'باینگان',N'باینگان',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (805,N'بیستون',N'بیستون',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (806,N'پاوه',N'پاوه',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (807,N'تازه آباد',N'تازه-آباد',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (808,N'جوان رود',N'جوان-رود',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (809,N'حمیل',N'حمیل',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (810,N'ماهیدشت',N'ماهیدشت',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (811,N'روانسر',N'روانسر',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (812,N'سرپل ذهاب',N'سرپل-ذهاب',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (813,N'سرمست',N'سرمست',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (814,N'سطر',N'سطر',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (815,N'سنقر',N'سنقر',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (816,N'سومار',N'سومار',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (817,N'شاهو',N'شاهو',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (818,N'صحنه',N'صحنه',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (819,N'قصرشیرین',N'قصرشیرین',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (820,N'کرمانشاه',N'کرمانشاه',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (821,N'کرندغرب',N'کرندغرب',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (822,N'کنگاور',N'کنگاور',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (823,N'کوزران',N'کوزران',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (824,N'گهواره',N'گهواره',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (825,N'گیلانغرب',N'گیلانغرب',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (826,N'میان راهان',N'میان-راهان',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (827,N'نودشه',N'نودشه',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (828,N'نوسود',N'نوسود',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (829,N'هرسین',N'هرسین',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (830,N'هلشی',N'هلشی',22);
INSERT INTO cities(id,name,slug,province_id) VALUES (831,N'باشت',N'باشت',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (832,N'پاتاوه',N'پاتاوه',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (833,N'چرام',N'چرام',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (834,N'چیتاب',N'چیتاب',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (835,N'دهدشت',N'دهدشت',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (836,N'دوگنبدان',N'دوگنبدان',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (837,N'دیشموک',N'دیشموک',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (838,N'سوق',N'سوق',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (839,N'سی سخت',N'سی-سخت',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (840,N'قلعه رئیسی',N'قلعه-رئیسی',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (841,N'گراب سفلی',N'گراب-سفلی',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (842,N'لنده',N'لنده',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (843,N'لیکک',N'لیکک',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (844,N'مادوان',N'مادوان',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (845,N'مارگون',N'مارگون',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (846,N'یاسوج',N'یاسوج',23);
INSERT INTO cities(id,name,slug,province_id) VALUES (847,N'انبارآلوم',N'انبارآلوم',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (848,N'اینچه برون',N'اینچه-برون',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (849,N'آزادشهر',N'آزادشهر',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (850,N'آق قلا',N'آق-قلا',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (851,N'بندرترکمن',N'بندرترکمن',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (852,N'بندرگز',N'بندرگز',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (853,N'جلین',N'جلین',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (854,N'خان ببین',N'خان-ببین',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (855,N'دلند',N'دلند',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (856,N'رامیان',N'رامیان',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (857,N'سرخنکلاته',N'سرخنکلاته',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (858,N'سیمین شهر',N'سیمین-شهر',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (859,N'علی آباد کتول',N'علی-آباد-کتول',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (860,N'فاضل آباد',N'فاضل-آباد',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (861,N'کردکوی',N'کردکوی',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (862,N'کلاله',N'کلاله',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (863,N'گالیکش',N'گالیکش',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (864,N'گرگان',N'گرگان',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (865,N'گمیش تپه',N'گمیش-تپه',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (866,N'گنبدکاووس',N'گنبدکاووس',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (867,N'مراوه',N'مراوه',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (868,N'مینودشت',N'مینودشت',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (869,N'نگین شهر',N'نگین-شهر',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (870,N'نوده خاندوز',N'نوده-خاندوز',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (871,N'نوکنده',N'نوکنده',24);
INSERT INTO cities(id,name,slug,province_id) VALUES (872,N'ازنا',N'ازنا',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (873,N'اشترینان',N'اشترینان',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (874,N'الشتر',N'الشتر',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (875,N'الیگودرز',N'الیگودرز',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (876,N'بروجرد',N'بروجرد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (877,N'پلدختر',N'پلدختر',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (878,N'چالانچولان',N'چالانچولان',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (879,N'چغلوندی',N'چغلوندی',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (880,N'چقابل',N'چقابل',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (881,N'خرم آباد',N'لرستان-خرم-آباد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (882,N'درب گنبد',N'درب-گنبد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (883,N'دورود',N'دورود',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (884,N'زاغه',N'زاغه',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (885,N'سپیددشت',N'سپیددشت',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (886,N'سراب دوره',N'سراب-دوره',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (887,N'فیروزآباد',N'لرستان-فیروزآباد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (888,N'کونانی',N'کونانی',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (889,N'کوهدشت',N'کوهدشت',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (890,N'گراب',N'گراب',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (891,N'معمولان',N'معمولان',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (892,N'مومن آباد',N'مومن-آباد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (893,N'نورآباد',N'لرستان-نورآباد',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (894,N'ویسیان',N'ویسیان',25);
INSERT INTO cities(id,name,slug,province_id) VALUES (895,N'احمدسرگوراب',N'احمدسرگوراب',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (896,N'اسالم',N'اسالم',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (897,N'اطاقور',N'اطاقور',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (898,N'املش',N'املش',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (899,N'آستارا',N'آستارا',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (900,N'آستانه اشرفیه',N'آستانه-اشرفیه',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (901,N'بازار جمعه',N'بازار-جمعه',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (902,N'بره سر',N'بره-سر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (903,N'بندرانزلی',N'بندرانزلی',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (906,N'پره سر',N'پره-سر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (907,N'تالش',N'تالش',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (908,N'توتکابن',N'توتکابن',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (909,N'جیرنده',N'جیرنده',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (910,N'چابکسر',N'چابکسر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (911,N'چاف و چمخاله',N'چاف-و-چمخاله',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (912,N'چوبر',N'چوبر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (913,N'حویق',N'حویق',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (914,N'خشکبیجار',N'خشکبیجار',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (915,N'خمام',N'خمام',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (916,N'دیلمان',N'دیلمان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (917,N'رانکوه',N'رانکوه',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (918,N'رحیم آباد',N'رحیم-آباد',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (919,N'رستم آباد',N'رستم-آباد',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (920,N'رشت',N'رشت',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (921,N'رضوانشهر',N'گیلان-رضوانشهر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (922,N'رودبار',N'گیلان-رودبار',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (923,N'رودبنه',N'رودبنه',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (924,N'رودسر',N'رودسر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (925,N'سنگر',N'سنگر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (926,N'سیاهکل',N'سیاهکل',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (927,N'شفت',N'شفت',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (928,N'شلمان',N'شلمان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (929,N'صومعه سرا',N'صومعه-سرا',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (930,N'فومن',N'فومن',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (931,N'کلاچای',N'کلاچای',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (932,N'کوچصفهان',N'کوچصفهان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (933,N'کومله',N'کومله',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (934,N'کیاشهر',N'کیاشهر',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (935,N'گوراب زرمیخ',N'گوراب-زرمیخ',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (936,N'لاهیجان',N'لاهیجان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (937,N'لشت نشا',N'لشت-نشا',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (938,N'لنگرود',N'لنگرود',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (939,N'لوشان',N'لوشان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (940,N'لولمان',N'لولمان',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (941,N'لوندویل',N'لوندویل',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (942,N'لیسار',N'لیسار',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (943,N'ماسال',N'ماسال',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (944,N'ماسوله',N'ماسوله',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (945,N'مرجقل',N'مرجقل',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (946,N'منجیل',N'منجیل',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (947,N'واجارگاه',N'واجارگاه',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (948,N'امیرکلا',N'امیرکلا',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (949,N'ایزدشهر',N'ایزدشهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (950,N'آلاشت',N'آلاشت',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (951,N'آمل',N'آمل',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (952,N'بابل',N'بابل',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (953,N'بابلسر',N'بابلسر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (954,N'بلده',N'مازندران-بلده',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (955,N'بهشهر',N'بهشهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (956,N'بهنمیر',N'بهنمیر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (957,N'پل سفید',N'پل-سفید',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (958,N'تنکابن',N'تنکابن',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (959,N'جویبار',N'جویبار',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (960,N'چالوس',N'چالوس',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (961,N'چمستان',N'چمستان',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (962,N'خرم آباد',N'مازندران-خرم-آباد',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (963,N'خلیل شهر',N'خلیل-شهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (964,N'خوش رودپی',N'خوش-رودپی',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (965,N'دابودشت',N'دابودشت',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (966,N'رامسر',N'رامسر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (967,N'رستمکلا',N'رستمکلا',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (968,N'رویان',N'رویان',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (969,N'رینه',N'رینه',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (970,N'زرگرمحله',N'زرگرمحله',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (971,N'زیرآب',N'زیرآب',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (972,N'ساری',N'ساری',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (973,N'سرخرود',N'سرخرود',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (974,N'سلمان شهر',N'سلمان-شهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (975,N'سورک',N'سورک',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (976,N'شیرگاه',N'شیرگاه',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (977,N'شیرود',N'شیرود',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (978,N'عباس آباد',N'عباس-آباد',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (979,N'فریدونکنار',N'فریدونکنار',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (980,N'فریم',N'فریم',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (981,N'قائم شهر',N'قائم-شهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (982,N'کتالم',N'کتالم',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (983,N'کلارآباد',N'کلارآباد',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (984,N'کلاردشت',N'کلاردشت',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (985,N'کله بست',N'کله-بست',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (986,N'کوهی خیل',N'کوهی-خیل',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (987,N'کیاسر',N'کیاسر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (988,N'کیاکلا',N'کیاکلا',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (989,N'گتاب',N'گتاب',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (990,N'گزنک',N'گزنک',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (991,N'گلوگاه',N'گلوگاه',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (992,N'محمودآباد',N'مازندران-محمودآباد',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (993,N'مرزن آباد',N'مرزن-آباد',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (994,N'مرزیکلا',N'مرزیکلا',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (995,N'نشتارود',N'نشتارود',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (996,N'نکا',N'نکا',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (997,N'نور',N'نور',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (998,N'نوشهر',N'نوشهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (999,N'اراک',N'اراک',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1000,N'آستانه',N'آستانه',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1001,N'آشتیان',N'آشتیان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1002,N'پرندک',N'پرندک',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1003,N'تفرش',N'تفرش',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1004,N'توره',N'توره',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1005,N'جاورسیان',N'جاورسیان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1006,N'خشکرود',N'خشکرود',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1007,N'خمین',N'خمین',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1008,N'خنداب',N'خنداب',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1009,N'داودآباد',N'داودآباد',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1010,N'دلیجان',N'دلیجان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1011,N'رازقان',N'رازقان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1012,N'زاویه',N'زاویه',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1013,N'ساروق',N'ساروق',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1014,N'ساوه',N'ساوه',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1015,N'سنجان',N'سنجان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1016,N'شازند',N'شازند',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1017,N'غرق آباد',N'غرق-آباد',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1018,N'فرمهین',N'فرمهین',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1019,N'قورچی باشی',N'قورچی-باشی',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1020,N'کرهرود',N'کرهرود',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1021,N'کمیجان',N'کمیجان',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1022,N'مامونیه',N'مامونیه',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1023,N'محلات',N'محلات',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1024,N'مهاجران',N'مهاجران',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1025,N'میلاجرد',N'میلاجرد',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1026,N'نراق',N'نراق',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1027,N'نوبران',N'نوبران',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1028,N'نیمور',N'نیمور',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1029,N'هندودر',N'هندودر',28);
INSERT INTO cities(id,name,slug,province_id) VALUES (1030,N'ابوموسی',N'ابوموسی',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1031,N'بستک',N'بستک',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1032,N'بندرجاسک',N'بندرجاسک',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1033,N'بندرچارک',N'بندرچارک',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1034,N'بندرخمیر',N'بندرخمیر',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1035,N'بندرعباس',N'بندرعباس',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1036,N'بندرلنگه',N'بندرلنگه',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1037,N'بیکا',N'بیکا',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1038,N'پارسیان',N'پارسیان',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1039,N'تخت',N'تخت',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1040,N'جناح',N'جناح',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1041,N'حاجی آباد',N'هرمزگان-حاجی-آباد',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1042,N'درگهان',N'درگهان',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1043,N'دهبارز',N'دهبارز',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1044,N'رویدر',N'رویدر',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1045,N'زیارتعلی',N'زیارتعلی',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1046,N'سردشت',N'هرمزگان-سردشت',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1047,N'سندرک',N'سندرک',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1048,N'سوزا',N'سوزا',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1049,N'سیریک',N'سیریک',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1050,N'فارغان',N'فارغان',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1051,N'فین',N'فین',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1052,N'قشم',N'قشم',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1053,N'قلعه قاضی',N'قلعه-قاضی',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1054,N'کنگ',N'کنگ',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1055,N'کوشکنار',N'کوشکنار',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1056,N'کیش',N'کیش',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1057,N'گوهران',N'گوهران',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1058,N'میناب',N'میناب',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1059,N'هرمز',N'هرمز',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1060,N'هشتبندی',N'هشتبندی',29);
INSERT INTO cities(id,name,slug,province_id) VALUES (1061,N'ازندریان',N'ازندریان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1062,N'اسدآباد',N'اسدآباد',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1063,N'برزول',N'برزول',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1064,N'بهار',N'بهار',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1065,N'تویسرکان',N'تویسرکان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1066,N'جورقان',N'جورقان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1067,N'جوکار',N'جوکار',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1068,N'دمق',N'دمق',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1069,N'رزن',N'رزن',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1070,N'زنگنه',N'زنگنه',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1071,N'سامن',N'سامن',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1072,N'سرکان',N'سرکان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1073,N'شیرین سو',N'شیرین-سو',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1074,N'صالح آباد',N'همدان-صالح-آباد',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1075,N'فامنین',N'فامنین',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1076,N'فرسفج',N'فرسفج',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1077,N'فیروزان',N'فیروزان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1078,N'قروه درجزین',N'قروه-درجزین',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1079,N'قهاوند',N'قهاوند',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1080,N'کبودر آهنگ',N'کبودر-آهنگ',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1081,N'گل تپه',N'گل-تپه',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1082,N'گیان',N'گیان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1083,N'لالجین',N'لالجین',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1084,N'مریانج',N'مریانج',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1085,N'ملایر',N'ملایر',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1086,N'نهاوند',N'نهاوند',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1087,N'همدان',N'همدان',30);
INSERT INTO cities(id,name,slug,province_id) VALUES (1088,N'ابرکوه',N'ابرکوه',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1089,N'احمدآباد',N'احمدآباد',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1090,N'اردکان',N'یزد-اردکان',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1091,N'اشکذر',N'اشکذر',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1092,N'بافق',N'بافق',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1093,N'بفروئیه',N'بفروئیه',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1094,N'بهاباد',N'بهاباد',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1095,N'تفت',N'تفت',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1096,N'حمیدیا',N'حمیدیا',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1097,N'خضرآباد',N'خضرآباد',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1098,N'دیهوک',N'دیهوک',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1099,N'زارچ',N'زارچ',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1100,N'شاهدیه',N'شاهدیه',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1101,N'طبس',N'یزد-طبس',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1103,N'عقدا',N'عقدا',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1104,N'مروست',N'مروست',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1105,N'مهردشت',N'مهردشت',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1106,N'مهریز',N'مهریز',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1107,N'میبد',N'میبد',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1108,N'ندوشن',N'ندوشن',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1109,N'نیر',N'یزد-نیر',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1110,N'هرات',N'هرات',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1111,N'یزد',N'یزد',31);
INSERT INTO cities(id,name,slug,province_id) VALUES (1116,N'پرند',N'پرند',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (1117,N'فردیس',N'فردیس',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (1118,N'مارلیک',N'مارلیک',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (1119,N'سادات شهر',N'سادات-شهر',27);
INSERT INTO cities(id,name,slug,province_id) VALUES (1121,N'زیباکنار',N'زیباکنار',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (1135,N'کردان',N'کردان',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (1137,N'ساوجبلاغ',N'ساوجبلاغ',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (1138,N'تهران دشت',N'تهران-دشت',5);
INSERT INTO cities(id,name,slug,province_id) VALUES (1150,N'گلبهار',N'گلبهار',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (1153,N'قیامدشت',N'قیامدشت',8);
INSERT INTO cities(id,name,slug,province_id) VALUES (1155,N'بینالود',N'بینالود',11);
INSERT INTO cities(id,name,slug,province_id) VALUES (1159,N'پیربازار',N'پیربازار',26);
INSERT INTO cities(id,name,slug,province_id) VALUES (1160,N'رضوانشهر',N'رضوانشهر',31);