import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import * as XLSX from "xlsx";
import { DatasetName, Datasets, PublicRecord } from "./types";
import { schema, validateDatasets } from "./schema";
const names: DatasetName[] = ["provinces", "counties", "districts", "rurals", "cities", "cities-filtered", "villages", "all"];
const nl = "\n";
export const sha256 = (data: Buffer | string) => crypto.createHash("sha256").update(data).digest("hex");
const csvCell = (value: string | number | null) => { const text = value === null ? "" : String(value); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; };
const headersFor = (records: PublicRecord[]) => [...new Set(records.flatMap((record) => Object.keys(record)))];
const csv = (records: PublicRecord[]) => { const headers = headersFor(records); return [headers.join(","), ...records.map((r) => headers.map((h) => csvCell(r[h] ?? null)).join(","))].join(nl) + nl; };
const norm = (record: Record<string, unknown>) => Object.fromEntries(Object.entries(record).map(([k, v]) => [k, v === null || v === undefined ? "" : String(v)]));
function same(expected: Record<string, unknown>, actual: Record<string, unknown>): boolean { const left = norm(expected), right = norm(actual); return Object.entries(left).every(([key, value]) => right[key] === value) && Object.entries(right).every(([key, value]) => key in left || value === ""); }
function parseCsv(content: string): Record<string, string>[] { const rows: string[][] = [[]]; let value = "", quoted = false; for (let i = 0; i < content.length; i += 1) { const char = content[i]; if (quoted) { if (char === '"' && content[i + 1] === '"') { value += '"'; i += 1; } else if (char === '"') quoted = false; else value += char; } else if (char === '"') quoted = true; else if (char === ",") { rows.at(-1)!.push(value); value = ""; } else if (char === "\n") { rows.at(-1)!.push(value); value = ""; if (i !== content.length - 1) rows.push([]); } else if (char !== "\r") value += char; } const [headers, ...data] = rows; return data.filter((row) => row.length > 1 || row[0] !== "").map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? ""]))); }
function writeXlsx(file: string, records: PublicRecord[]): void { const book = XLSX.utils.book_new(); const sheet = XLSX.utils.json_to_sheet(records, { header: headersFor(records) }); XLSX.utils.book_append_sheet(book, sheet, "Sheet1"); fs.writeFileSync(file, XLSX.write(book, { type: "buffer", bookType: "xlsx", compression: false })); }
export function writeDatasets(root: string, datasets: Datasets): void { validateDatasets(datasets); for (const d of ["json", "csv", "xlsx"]) fs.mkdirSync(path.join(root, d), { recursive: true }); for (const name of names) { const rows = datasets[name]; fs.writeFileSync(path.join(root, "json", `${name}.json`), `${JSON.stringify(rows, null, 2)}${nl}`, "utf8"); fs.writeFileSync(path.join(root, "csv", `${name}.csv`), csv(rows), "utf8"); writeXlsx(path.join(root, "xlsx", `${name}.xlsx`), rows); } }
export function verifyFormatParity(root: string): Record<DatasetName, number> { const counts = {} as Record<DatasetName, number>; for (const name of names) { const json = JSON.parse(fs.readFileSync(path.join(root, "json", `${name}.json`), "utf8")) as PublicRecord[]; const csvRows = parseCsv(fs.readFileSync(path.join(root, "csv", `${name}.csv`), "utf8")); const book = XLSX.readFile(path.join(root, "xlsx", `${name}.xlsx`), { cellText: true }); const xlsxRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(book.Sheets[book.SheetNames[0]], { defval: "", raw: true }); if (json.length !== csvRows.length || json.length !== xlsxRows.length) throw new Error(`Format row-count parity failed for ${name}`); for (let i = 0; i < json.length; i += 1) if (!same(json[i], csvRows[i]) || !same(json[i], xlsxRows[i])) throw new Error(`Format semantic parity failed for ${name} record ${i}`); counts[name] = json.length; } return counts; }
export const writeSchema = (root: string) => fs.writeFileSync(path.join(root, "schema.json"), `${JSON.stringify(schema, null, 2)}${nl}`, "utf8");
export function validateJsonOutputs(root: string): void { const datasets = Object.fromEntries(names.map((name) => [name, JSON.parse(fs.readFileSync(path.join(root, "json", `${name}.json`), "utf8"))])) as Datasets; validateDatasets(datasets); }
