import * as fs from "node:fs";
import * as path from "node:path";
import { assertAcyclic, buildCanonicalModel } from "./model";
import { loadV2Contract, loadV2RuralMigrationOverrides, legacyIdFor, RuralMigrationOverride, V2Contract, V2Dataset } from "./compat";
import { sha256, validateJsonOutputs, verifyCoordinateFormatParity, verifyFormatParity, writeCoordinateDatasets, writeDatasets, writeSchema } from "./output";
import { coordinateMetrics, loadCoordinateSources, validateCoordinateDatasets } from "./coordinates";
import { ExplorerVerification, verifyExplorerData, writeExplorerData } from "./explorer";
import { formatLlmContext, inspectLlmContext, LLM_SCOPES } from "./llm";
import { idFor, projectDatasets } from "./project";
import { combinedSchema, schemaResult } from "./schema";
import { parseOfficialWorkbook } from "./source";
import { CoordinateDatasets, DatasetName, Datasets, PublicRecord } from "./types";
import { loadUrbanZoneKeys, URBAN_ZONE_CLASSIFICATION_SOURCE } from "./urban-zones";
import { duplicatePublicIds, exactSubset, measureModel, unsafeIdentifiers } from "./validation";
import { normalizeMigrationName, normalizePersianText } from "./text";

const names: DatasetName[] = ["provinces", "counties", "districts", "rurals", "cities", "cities-filtered", "urban-zones", "villages", "all"];
export const MANIFEST_ENTITY_TYPES: Record<DatasetName, string> = { provinces: "province", counties: "county", districts: "district", rurals: "rural", cities: "city", "cities-filtered": "city", "urban-zones": "urban-zone", villages: "village", all: "mixed" };
export interface BuildResult { sourceSha256: string; sourceRows: number; coderecCounts: Record<string, number>; rowCounts: Record<DatasetName, number>; coordinateRowCounts: { "province-capitals": number; "county-centers": number }; }
interface Computed { result: BuildResult; datasets: Datasets; coordinates: CoordinateDatasets; coordinateRegistry: ReturnType<typeof loadCoordinateSources>["registry"]; coordinateEvidence: ReturnType<typeof loadCoordinateSources>["evidence"]; inspection: ReturnType<typeof parseOfficialWorkbook>["inspection"]; model: ReturnType<typeof buildCanonicalModel>; contract: V2Contract; }
function computed(repoRoot: string): Computed {
  const parsed = parseOfficialWorkbook(path.join(repoRoot, "offical", "list.xlsx")); const model = buildCanonicalModel(parsed.rows); assertAcyclic(model);
  const contract = loadV2Contract(repoRoot); const datasets = projectDatasets(model, contract, loadUrbanZoneKeys(repoRoot, model)); const coordinate = loadCoordinateSources(repoRoot);
  validateCoordinateDatasets(coordinate.datasets, datasets, coordinate.registry, coordinate.evidence);
  const result = { sourceSha256: sha256(fs.readFileSync(path.join(repoRoot, "offical", "list.xlsx"))), sourceRows: parsed.rows.length, coderecCounts: parsed.inspection.coderecCounts, rowCounts: Object.fromEntries(names.map((name) => [name, datasets[name].length])) as Record<DatasetName, number>, coordinateRowCounts: { "province-capitals": coordinate.datasets["province-capitals"].length, "county-centers": coordinate.datasets["county-centers"].length } };
  return { result, datasets, coordinates: coordinate.datasets, coordinateRegistry: coordinate.registry, coordinateEvidence: coordinate.evidence, inspection: parsed.inspection, model, contract };
}
export interface Migration { entity: "rural"; old_id: number; new_id: number | null; status: "matched" | "ambiguous" | "not_found"; match_basis: string; candidate_new_ids: number[]; }
export interface RuralMigrationCandidate { legacy_id: number; id: number; name: string; province_id?: number; county_id?: number; }
export function classifyRuralMigrationCandidates(old: V2Contract["datasets"]["rurals"][number], candidates: RuralMigrationCandidate[]): Migration {
  const matches = candidates.filter((candidate) => candidate.legacy_id === old.id && candidate.province_id === old.province_id && candidate.county_id === old.county_id && normalizeMigrationName(candidate.name) === normalizeMigrationName(old.name));
  const candidate_new_ids = matches.map((candidate) => candidate.id).sort((a, b) => a - b);
  const exactName = matches.length > 0 && matches.every((candidate) => normalizePersianText(candidate.name) === normalizePersianText(old.name));
  const match_basis = exactName ? "legacy-id-parent-and-name" : "legacy-id-province-county-normalized-name";
  if (candidate_new_ids.length === 1) return { entity: "rural", old_id: old.id, new_id: candidate_new_ids[0], status: "matched", match_basis, candidate_new_ids };
  if (candidate_new_ids.length > 1) return { entity: "rural", old_id: old.id, new_id: null, status: "ambiguous", match_basis, candidate_new_ids };
  return { entity: "rural", old_id: old.id, new_id: null, status: "not_found", match_basis: "no-current-legacy-id-province-county-normalized-name-match", candidate_new_ids: [] };
}
function applyRuralMigrationOverrides(model: Computed["model"], data: Datasets, contract: V2Contract, automaticMigrations: Migration[], overrides: RuralMigrationOverride[]): Migration[] {
  const historicalById = new Map(contract.datasets.rurals.map((record) => [record.id, record])); const automaticByOldId = new Map(automaticMigrations.map((migration) => [migration.old_id, migration])); const currentRurals = new Map(data.rurals.map((record) => [Number(record.id), record])); const seenOldIds = new Set<number>(); const seenTargetIds = new Set<number>(); const targets = new Map<number, number>();
  for (const override of overrides) {
    if (!override || typeof override.old_id !== "number" || typeof override.current_key !== "string" || typeof override.reason !== "string") throw new Error("Invalid rural migration override entry");
    if (!Number.isSafeInteger(override.old_id) || !historicalById.has(override.old_id)) throw new Error(`Rural migration override references unknown V2 rural ID ${override.old_id}`);
    if (override.reason !== "administrative_reorganization" && override.reason !== "official_name_change") throw new Error(`Rural migration override has invalid reason for V2 rural ID ${override.old_id}`);
    if (seenOldIds.has(override.old_id)) throw new Error(`Duplicate rural migration override old_id ${override.old_id}`); seenOldIds.add(override.old_id);
    const automatic = automaticByOldId.get(override.old_id); if (!automatic || automatic.status !== "not_found") throw new Error(`Rural migration override conflicts with automatic ${automatic?.status ?? "missing"} match for V2 rural ID ${override.old_id}`);
    const entities = model.entities.filter((entity) => entity.type === "rural" && entity.key === override.current_key); if (entities.length !== 1) throw new Error(`Rural migration override current_key must resolve to exactly one current rural: ${override.current_key}`);
    const targetId = Number(idFor(entities[0])); if (!currentRurals.has(targetId)) throw new Error(`Rural migration override current_key does not produce a current V3 rural ID: ${override.current_key}`);
    if (seenTargetIds.has(targetId)) throw new Error(`Duplicate rural migration override target V3 rural ID ${targetId}`); seenTargetIds.add(targetId); targets.set(override.old_id, targetId);
  }
  const migrated = automaticMigrations.map((migration) => { const targetId = targets.get(migration.old_id); return targetId === undefined ? migration : { entity: "rural" as const, old_id: migration.old_id, new_id: targetId, status: "matched" as const, match_basis: "compatibility_override", candidate_new_ids: [targetId] }; });
  if (new Set(migrated.map((migration) => migration.old_id)).size !== migrated.length) throw new Error("Rural migration overrides create duplicate migration rows");
  return migrated;
}
export function ruralMigrations(model: Computed["model"], data: Datasets, contract: V2Contract, overrides: RuralMigrationOverride[] = loadV2RuralMigrationOverrides(path.basename(process.cwd()) === "tools" ? path.resolve(process.cwd(), "..") : process.cwd())): Migration[] {
  const ruralById = new Map(data.rurals.map((record) => [String(record.id), record]));
  const candidates = model.entities.filter((entity) => entity.type === "rural").map((entity) => { const record = ruralById.get(String(idFor(entity)))!; return { legacy_id: legacyIdFor(entity), id: Number(record.id), name: String(record.name), province_id: record.province_id as number | undefined, county_id: record.county_id as number | undefined }; });
  return applyRuralMigrationOverrides(model, data, contract, contract.datasets.rurals.map((old) => classifyRuralMigrationCandidates(old, candidates)), overrides);
}
function migrationMetrics(migrations: Migration[], contract: V2Contract, data: Datasets) {
  const old = new Set(contract.datasets.rurals.map((record) => record.id)); const next = new Set(data.rurals.map((record) => Number(record.id)));
  const invalidOldIds = migrations.filter((record) => !old.has(record.old_id)).length;
  const invalidNewIds = migrations.filter((record) => record.new_id !== null && !next.has(record.new_id)).length + migrations.flatMap((record) => record.candidate_new_ids).filter((id) => !next.has(id)).length;
  return { v2Rows: old.size, migrationRecords: migrations.length, matched: migrations.filter((record) => record.status === "matched").length, ambiguous: migrations.filter((record) => record.status === "ambiguous").length, not_found: migrations.filter((record) => record.status === "not_found").length, normalizationMatches: migrations.filter((record) => record.status === "matched" && record.match_basis === "legacy-id-province-county-normalized-name").length, compatibilityOverrideMatches: migrations.filter((record) => record.status === "matched" && record.match_basis === "compatibility_override").length, invalidOldIds, invalidNewIds, complete: new Set(migrations.map((record) => record.old_id)).size === old.size && migrations.every((record) => old.has(record.old_id)) };
}
function migrationCsv(migrations: Migration[]): string { const rows = migrations.map((record) => `${record.entity},${record.old_id},${record.new_id ?? ""},${record.status},${record.match_basis},${record.candidate_new_ids.join("|")}`); return `entity,old_id,new_id,status,match_basis,candidate_new_ids\n${rows.join("\n")}\n`; }
function writeMigration(repoRoot: string, migrations: Migration[]): void { fs.writeFileSync(path.join(repoRoot, "migration", "v2-to-v3.csv"), migrationCsv(migrations), "utf8"); }
function compatibility(data: Datasets, contract: V2Contract) {
  const pairs: [V2Dataset, DatasetName][] = [["provinces", "provinces"], ["counties", "counties"], ["districts", "districts"], ["cities", "cities"]];
  return Object.fromEntries(pairs.map(([historicalName, currentName]) => { const historical = contract.datasets[historicalName]; const byId = new Map(historical.map((record) => [record.id, record])); const matches = data[currentName].filter((record) => byId.has(Number(record.id))); const idsPreserved = matches.filter((record) => byId.get(Number(record.id))!.id === record.id).length; return [historicalName, { historicalEntities: historical.length, historicalMatched: matches.length, historicalEntitiesMatched: matches.length, idsPreserved, idsChanged: matches.length - idsPreserved, slugsPreserved: matches.filter((record) => byId.get(Number(record.id))!.slug === record.slug).length, intentionalOrUnavoidableDifferences: historical.length - matches.length }]; }));
}
function llmContexts(datasets: Datasets): Record<string, string> { return Object.fromEntries(LLM_SCOPES.map((scope) => [scope, formatLlmContext(scope, datasets[scope], 1404)])); }
function writeLlmContexts(distRoot: string, datasets: Datasets): void { fs.mkdirSync(path.join(distRoot, "llm"), { recursive: true }); for (const [scope, content] of Object.entries(llmContexts(datasets))) fs.writeFileSync(path.join(distRoot, "llm", `${scope}.txt`), content, "utf8"); }
function manifest(result: BuildResult, registry: Computed["coordinateRegistry"]) { return { datasetVersion: "3.1.0", schemaVersion: "3.1.0", officialSourceYear: 1404, source: { filename: "offical/list.xlsx", sha256: result.sourceSha256 }, entityTypeContract: MANIFEST_ENTITY_TYPES, generatedDatasets: names.map((name) => ({ name, entityType: MANIFEST_ENTITY_TYPES[name], derived: name === "cities-filtered" || name === "urban-zones", rowCount: result.rowCounts[name], paths: { json: `dist/json/${name}.json`, csv: `dist/csv/${name}.csv`, xlsx: `dist/xlsx/${name}.xlsx` }, ...(["cities-filtered", "urban-zones"].includes(name) ? { partitionOf: "cities", classificationSource: URBAN_ZONE_CLASSIFICATION_SOURCE } : {}) })), enrichmentDatasets: [{ name: "province-capitals", entityType: "province-capital", enrichment: true, derived: true, officialAdministrativeSource: false, rowCount: result.coordinateRowCounts["province-capitals"], sourceIds: registry.sources.map((source) => source.id), paths: { json: "dist/json/province-capitals.json", csv: "dist/csv/province-capitals.csv", xlsx: "dist/xlsx/province-capitals.xlsx" } }, { name: "county-centers", entityType: "county-center", enrichment: true, derived: true, officialAdministrativeSource: false, rowCount: result.coordinateRowCounts["county-centers"], sourceIds: registry.sources.map((source) => source.id), paths: { json: "dist/json/county-centers.json", csv: "dist/csv/county-centers.csv", xlsx: "dist/xlsx/county-centers.xlsx" } }], enrichmentSources: registry.sources, llmContexts: LLM_SCOPES.map((scope) => ({ scope, entityType: scope === "provinces" ? "province" : scope === "counties" ? "county" : scope === "urban-zones" ? "urban-zone" : "city", rowCount: result.rowCounts[scope], path: `dist/llm/${scope}.txt`, format: "header+tsv", derived: true })), generator: { name: "list-of-cities-in-iran-tools", version: "3.1.0", deterministic: true } }; }
export function validateManifest(value: unknown): boolean { if (!value || typeof value !== "object") return false; const candidate = value as { entityTypeContract?: unknown; generatedDatasets?: unknown; enrichmentDatasets?: unknown; enrichmentSources?: unknown; llmContexts?: unknown }; if (JSON.stringify(candidate.entityTypeContract) !== JSON.stringify(MANIFEST_ENTITY_TYPES) || !Array.isArray(candidate.generatedDatasets) || candidate.generatedDatasets.length !== names.length || !Array.isArray(candidate.enrichmentDatasets) || candidate.enrichmentDatasets.length !== 2 || !Array.isArray(candidate.enrichmentSources) || !Array.isArray(candidate.llmContexts) || candidate.llmContexts.length !== LLM_SCOPES.length) return false; return candidate.generatedDatasets.every((dataset) => { if (!dataset || typeof dataset !== "object") return false; const item = dataset as { name?: DatasetName; entityType?: string }; return Boolean(item.name && item.entityType === MANIFEST_ENTITY_TYPES[item.name]); }) && candidate.enrichmentDatasets.every((dataset) => { const item = dataset as { enrichment?: unknown; officialAdministrativeSource?: unknown; sourceIds?: unknown }; return item.enrichment === true && item.officialAdministrativeSource === false && Array.isArray(item.sourceIds) && item.sourceIds.length > 0; }); }
function documentationCheck(repoRoot: string) { const readme = fs.readFileSync(path.join(repoRoot, "README.md"), "utf8"); const requiredPaths = ["dist/manifest.json", "dist/schema.json", "dist/llm/provinces.txt", "dist/llm/counties.txt", "dist/llm/cities-filtered.txt", "dist/llm/cities.txt", "dist/llm/urban-zones.txt", "dist/json/province-capitals.json", "dist/json/county-centers.json", "docs/llms.txt", "docs/index.html", "docs/assets/app.js", "docs/assets/explorer-core.js", "docs/assets/styles.css", "docs/data/explorer-meta.json", "docs/data/search-core.json", "docs/data/search-villages.json"]; const missingPaths = requiredPaths.filter((file) => !fs.existsSync(path.join(repoRoot, file))); const footer = "Made with ❤ by [Sajad Dehshiri](https://sajaddehshiri.ir)"; return { requiredPaths, missingPaths, quickStart: readme.includes("Which file should I use?"), cityCountySemantics: readme.includes("City = شهر") && readme.includes("County = شهرستان"), filteredSemantics: readme.includes("cities-filtered") && readme.includes("urban-zones"), manifestSchemaLinks: readme.includes("dist/manifest.json") && readme.includes("dist/schema.json"), footer: { exact: readme.split("\n").filter((line) => line.trim()).at(-1) === footer } }; }
function report(repoRoot: string, computedResult: Computed, migrations: Migration[], parity: ReturnType<typeof verifyFormatParity>, coordinateParity: ReturnType<typeof verifyCoordinateFormatParity>, explorer: ExplorerVerification) {
  const { result, inspection, model, datasets, coordinates, coordinateRegistry, coordinateEvidence, contract } = computedResult; const modelMetrics = measureModel(model); const schema = schemaResult(datasets); const migration = migrationMetrics(migrations, contract, datasets); const contexts = llmContexts(datasets); const llm = Object.fromEntries(LLM_SCOPES.map((scope) => [scope, inspectLlmContext(scope, contexts[scope])])) ;
  const cityIds = new Set(datasets.cities.map((record) => String(record.id))); const filteredIds = new Set(datasets["cities-filtered"].map((record) => String(record.id))); const urbanZoneIds = new Set(datasets["urban-zones"].map((record) => String(record.id))); const overlap = [...filteredIds].filter((id) => urbanZoneIds.has(id)).length; const partition = new Set([...filteredIds, ...urbanZoneIds]);
  return { version: "3.1.0", source: { year: 1404, filename: "offical/list.xlsx", sha256: result.sourceSha256, worksheet: inspection.worksheet, totalRows: inspection.totalRows, coderecCounts: inspection.coderecCounts, nullableColumns: inspection.nullableColumns, samplesByCoderec: inspection.samplesByCoderec }, validation: {
    supportedRows: result.sourceRows, unhandledRows: inspection.totalRows - result.sourceRows, ...modelMetrics, orphans: modelMetrics.missingParents, duplicatePublicIds: duplicatePublicIds(datasets), unsafeNumericIdentifiers: unsafeIdentifiers(model), jsonSchema: schema, formatParity: parity, rowCounts: result.rowCounts,
    cityPartition: { source: URBAN_ZONE_CLASSIFICATION_SOURCE, cities: datasets.cities.length, citiesFiltered: { realCities: true, rows: datasets["cities-filtered"].length, subset: exactSubset(datasets["cities-filtered"], datasets.cities) }, urbanZones: { rows: datasets["urban-zones"].length, subset: exactSubset(datasets["urban-zones"], datasets.cities) }, overlap, complete: partition.size === cityIds.size && [...partition].every((id) => cityIds.has(id)) }, villages: { sourceCoderecs: ["6", "8"], accountedRows: inspection.coderecCounts["6"] + inspection.coderecCounts["8"] },
    manifest: { passed: validateManifest(manifest(result, coordinateRegistry)), entityTypes: MANIFEST_ENTITY_TYPES }, llm: { contexts: llm, deterministic: LLM_SCOPES.every((scope) => contexts[scope] === formatLlmContext(scope, datasets[scope], 1404)), noUnexpectedArtifacts: true }, coordinates: { ...coordinateMetrics(coordinates, datasets, coordinateRegistry, coordinateEvidence), formatParity: coordinateParity, provenanceSources: coordinateRegistry.sources }, explorer, documentation: documentationCheck(repoRoot), v2Compatibility: compatibility(datasets, contract), migration,
    idStrategy: { legacyPublicIds: "V2 formulas parse source segments numerically; canonical keys retain padded source strings", rural: "V3 fixed-width district+rural suffix prevents V2 cross-district collisions", villages: "namespaced, delimiter-separated source-code IDs" }, allContract: { fields: ["id", "type", "name", "slug", "tel_prefix", "province_id", "county_id", "district_id", "rural_id", "coderec", "village_code", "mapped_rural_code"], nullableTabularCellsDecodeAs: "null" },
  } };
}
export function buildPipeline(repoRoot: string, distRoot = path.join(repoRoot, "dist")): BuildResult { const value = computed(repoRoot); fs.mkdirSync(distRoot, { recursive: true }); writeDatasets(distRoot, value.datasets); writeCoordinateDatasets(distRoot, value.coordinates); writeLlmContexts(distRoot, value.datasets); writeSchema(distRoot); const migrations = ruralMigrations(value.model, value.datasets, value.contract); writeMigration(repoRoot, migrations); const parity = verifyFormatParity(distRoot); const coordinateParity = verifyCoordinateFormatParity(distRoot); if (!parity.passed || !coordinateParity.passed) throw new Error(`Format parity failed: ${[...parity.errors, ...coordinateParity.errors].join("; ")}`); validateJsonOutputs(distRoot); const generatedManifest = manifest(value.result, value.coordinateRegistry); fs.writeFileSync(path.join(distRoot, "manifest.json"), `${JSON.stringify(generatedManifest, null, 2)}\n`, "utf8"); writeExplorerData(repoRoot, value.datasets, value.coordinates, generatedManifest); const explorer = verifyExplorerData(repoRoot, value.datasets, value.coordinates, generatedManifest); fs.writeFileSync(path.join(distRoot, "verification.json"), `${JSON.stringify(report(repoRoot, value, migrations, parity, coordinateParity, explorer), null, 2)}\n`, "utf8"); return value.result; }
export function verifyPipeline(repoRoot: string): BuildResult { const distRoot = path.join(repoRoot, "dist"); const value = computed(repoRoot); validateJsonOutputs(distRoot); const parity = verifyFormatParity(distRoot); const coordinateParity = verifyCoordinateFormatParity(distRoot); if (!parity.passed || !coordinateParity.passed) throw new Error(`Format parity failed: ${[...parity.errors, ...coordinateParity.errors].join("; ")}`); if (JSON.stringify(JSON.parse(fs.readFileSync(path.join(distRoot, "schema.json"), "utf8"))) !== JSON.stringify(combinedSchema)) throw new Error("Schema is stale or invalid"); for (const name of names) { const actual = JSON.parse(fs.readFileSync(path.join(distRoot, "json", `${name}.json`), "utf8")); if (JSON.stringify(actual) !== JSON.stringify(value.datasets[name])) throw new Error(`Generated JSON is stale for ${name}`); } for (const name of ["province-capitals", "county-centers"] as const) { const actual = JSON.parse(fs.readFileSync(path.join(distRoot, "json", `${name}.json`), "utf8")); if (JSON.stringify(actual) !== JSON.stringify(value.coordinates[name])) throw new Error(`Generated coordinate JSON is stale for ${name}`); } for (const [scope, expected] of Object.entries(llmContexts(value.datasets))) { const actual = fs.readFileSync(path.join(distRoot, "llm", `${scope}.txt`), "utf8"); if (actual !== expected) throw new Error(`LLM context is stale for ${scope}`); inspectLlmContext(scope as DatasetName, actual); }
  const migrations = ruralMigrations(value.model, value.datasets, value.contract); const metrics = migrationMetrics(migrations, value.contract, value.datasets); if (!metrics.complete || metrics.invalidOldIds || metrics.invalidNewIds || fs.readFileSync(path.join(repoRoot, "migration", "v2-to-v3.csv"), "utf8") !== migrationCsv(migrations)) throw new Error("Migration contract is invalid or stale"); const actualManifest = JSON.parse(fs.readFileSync(path.join(distRoot, "manifest.json"), "utf8")); if (!validateManifest(actualManifest) || JSON.stringify(actualManifest) !== JSON.stringify(manifest(value.result, value.coordinateRegistry))) throw new Error("Manifest is stale or invalid"); const explorer = verifyExplorerData(repoRoot, value.datasets, value.coordinates, actualManifest); const actualReport = JSON.parse(fs.readFileSync(path.join(distRoot, "verification.json"), "utf8")); if (JSON.stringify(actualReport) !== JSON.stringify(report(repoRoot, value, migrations, parity, coordinateParity, explorer))) throw new Error("Verification report is stale"); return value.result; }
