/*
 Source Server         : Localhost
 Source Server Type    : MySQL
 Source Server Version : 100130
 Source Host           : localhost:3306

 Target Server Type    : MySQL
 Target Server Version : 100130
 File Encoding         : 65001

 Date: 01/03/2018 11:47:01
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for cities
-- ----------------------------
DROP TABLE IF EXISTS `cities`;
CREATE TABLE `cities`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `province_id` int(11) NOT NULL,
  `name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `active` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `cities_slug_unique`(`slug`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1120 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cities
-- ----------------------------
INSERT INTO `cities` VALUES (1, 1, 'اسکو', 'اسکو', '0');
INSERT INTO `cities` VALUES (2, 1, 'اهر', 'اهر', '0');
INSERT INTO `cities` VALUES (3, 1, 'ایلخچی', 'ایلخچی', '0');
INSERT INTO `cities` VALUES (4, 1, 'آبش احمد', 'آبش-احمد', '0');
INSERT INTO `cities` VALUES (5, 1, 'آذرشهر', 'آذرشهر', '0');
INSERT INTO `cities` VALUES (6, 1, 'آقکند', 'آقکند', '0');
INSERT INTO `cities` VALUES (7, 1, 'باسمنج', 'باسمنج', '0');
INSERT INTO `cities` VALUES (8, 1, 'بخشایش', 'بخشایش', '0');
INSERT INTO `cities` VALUES (9, 1, 'بستان آباد', 'بستان-آباد', '0');
INSERT INTO `cities` VALUES (10, 1, 'بناب', 'بناب', '0');
INSERT INTO `cities` VALUES (11, 1, 'بناب جدید', 'بناب-جدید', '0');
INSERT INTO `cities` VALUES (12, 1, 'تبریز', 'تبریز', '0');
INSERT INTO `cities` VALUES (13, 1, 'ترک', 'ترک', '0');
INSERT INTO `cities` VALUES (14, 1, 'ترکمانچای', 'ترکمانچای', '0');
INSERT INTO `cities` VALUES (15, 1, 'تسوج', 'تسوج', '0');
INSERT INTO `cities` VALUES (16, 1, 'تیکمه داش', 'تیکمه-داش', '0');
INSERT INTO `cities` VALUES (17, 1, 'جلفا', 'جلفا', '0');
INSERT INTO `cities` VALUES (18, 1, 'خاروانا', 'خاروانا', '0');
INSERT INTO `cities` VALUES (19, 1, 'خامنه', 'خامنه', '0');
INSERT INTO `cities` VALUES (20, 1, 'خراجو', 'خراجو', '0');
INSERT INTO `cities` VALUES (21, 1, 'خسروشهر', 'خسروشهر', '0');
INSERT INTO `cities` VALUES (22, 1, 'خضرلو', 'خضرلو', '0');
INSERT INTO `cities` VALUES (23, 1, 'خمارلو', 'خمارلو', '0');
INSERT INTO `cities` VALUES (24, 1, 'خواجه', 'خواجه', '0');
INSERT INTO `cities` VALUES (25, 1, 'دوزدوزان', 'دوزدوزان', '0');
INSERT INTO `cities` VALUES (26, 1, 'زرنق', 'زرنق', '0');
INSERT INTO `cities` VALUES (27, 1, 'زنوز', 'زنوز', '0');
INSERT INTO `cities` VALUES (28, 1, 'سراب', 'سراب', '0');
INSERT INTO `cities` VALUES (29, 1, 'سردرود', 'سردرود', '0');
INSERT INTO `cities` VALUES (30, 1, 'سهند', 'سهند', '0');
INSERT INTO `cities` VALUES (31, 1, 'سیس', 'سیس', '0');
INSERT INTO `cities` VALUES (32, 1, 'سیه رود', 'سیه-رود', '0');
INSERT INTO `cities` VALUES (33, 1, 'شبستر', 'شبستر', '0');
INSERT INTO `cities` VALUES (34, 1, 'شربیان', 'شربیان', '0');
INSERT INTO `cities` VALUES (35, 1, 'شرفخانه', 'شرفخانه', '0');
INSERT INTO `cities` VALUES (36, 1, 'شندآباد', 'شندآباد', '0');
INSERT INTO `cities` VALUES (37, 1, 'صوفیان', 'صوفیان', '0');
INSERT INTO `cities` VALUES (38, 1, 'عجب شیر', 'عجب-شیر', '0');
INSERT INTO `cities` VALUES (39, 1, 'قره آغاج', 'قره-آغاج', '0');
INSERT INTO `cities` VALUES (40, 1, 'کشکسرای', 'کشکسرای', '0');
INSERT INTO `cities` VALUES (41, 1, 'کلوانق', 'کلوانق', '0');
INSERT INTO `cities` VALUES (42, 1, 'کلیبر', 'کلیبر', '0');
INSERT INTO `cities` VALUES (43, 1, 'کوزه کنان', 'کوزه-کنان', '0');
INSERT INTO `cities` VALUES (44, 1, 'گوگان', 'گوگان', '0');
INSERT INTO `cities` VALUES (45, 1, 'لیلان', 'لیلان', '0');
INSERT INTO `cities` VALUES (46, 1, 'مراغه', 'مراغه', '0');
INSERT INTO `cities` VALUES (47, 1, 'مرند', 'مرند', '0');
INSERT INTO `cities` VALUES (48, 1, 'ملکان', 'ملکان', '0');
INSERT INTO `cities` VALUES (49, 1, 'ملک کیان', 'ملک-کیان', '0');
INSERT INTO `cities` VALUES (50, 1, 'ممقان', 'ممقان', '0');
INSERT INTO `cities` VALUES (51, 1, 'مهربان', 'مهربان', '0');
INSERT INTO `cities` VALUES (52, 1, 'میانه', 'میانه', '0');
INSERT INTO `cities` VALUES (53, 1, 'نظرکهریزی', 'نظرکهریزی', '0');
INSERT INTO `cities` VALUES (54, 1, 'هادی شهر', 'هادی-شهر', '0');
INSERT INTO `cities` VALUES (55, 1, 'هرگلان', 'هرگلان', '0');
INSERT INTO `cities` VALUES (56, 1, 'هریس', 'هریس', '0');
INSERT INTO `cities` VALUES (57, 1, 'هشترود', 'هشترود', '0');
INSERT INTO `cities` VALUES (58, 1, 'هوراند', 'هوراند', '0');
INSERT INTO `cities` VALUES (59, 1, 'وایقان', 'وایقان', '0');
INSERT INTO `cities` VALUES (60, 1, 'ورزقان', 'ورزقان', '0');
INSERT INTO `cities` VALUES (61, 1, 'یامچی', 'یامچی', '0');
INSERT INTO `cities` VALUES (62, 2, 'ارومیه', 'ارومیه', '0');
INSERT INTO `cities` VALUES (63, 2, 'اشنویه', 'اشنویه', '0');
INSERT INTO `cities` VALUES (64, 2, 'ایواوغلی', 'ایواوغلی', '0');
INSERT INTO `cities` VALUES (65, 2, 'آواجیق', 'آواجیق', '0');
INSERT INTO `cities` VALUES (66, 2, 'باروق', 'باروق', '0');
INSERT INTO `cities` VALUES (67, 2, 'بازرگان', 'بازرگان', '0');
INSERT INTO `cities` VALUES (68, 2, 'بوکان', 'بوکان', '0');
INSERT INTO `cities` VALUES (69, 2, 'پلدشت', 'پلدشت', '0');
INSERT INTO `cities` VALUES (70, 2, 'پیرانشهر', 'پیرانشهر', '0');
INSERT INTO `cities` VALUES (71, 2, 'تازه شهر', 'تازه-شهر', '0');
INSERT INTO `cities` VALUES (72, 2, 'تکاب', 'تکاب', '0');
INSERT INTO `cities` VALUES (73, 2, 'چهاربرج', 'چهاربرج', '0');
INSERT INTO `cities` VALUES (74, 2, 'خوی', 'خوی', '0');
INSERT INTO `cities` VALUES (75, 2, 'دیزج دیز', 'دیزج-دیز', '0');
INSERT INTO `cities` VALUES (76, 2, 'ربط', 'ربط', '0');
INSERT INTO `cities` VALUES (77, 2, 'سردشت', 'آذربایجان-غربی-سردشت', '0');
INSERT INTO `cities` VALUES (78, 2, 'سرو', 'سرو', '0');
INSERT INTO `cities` VALUES (79, 2, 'سلماس', 'سلماس', '0');
INSERT INTO `cities` VALUES (80, 2, 'سیلوانه', 'سیلوانه', '0');
INSERT INTO `cities` VALUES (81, 2, 'سیمینه', 'سیمینه', '0');
INSERT INTO `cities` VALUES (82, 2, 'سیه چشمه', 'سیه-چشمه', '0');
INSERT INTO `cities` VALUES (83, 2, 'شاهین دژ', 'شاهین-دژ', '0');
INSERT INTO `cities` VALUES (84, 2, 'شوط', 'شوط', '0');
INSERT INTO `cities` VALUES (85, 2, 'فیرورق', 'فیرورق', '0');
INSERT INTO `cities` VALUES (86, 2, 'قره ضیاءالدین', 'قره-ضیاءالدین', '0');
INSERT INTO `cities` VALUES (87, 2, 'قطور', 'قطور', '0');
INSERT INTO `cities` VALUES (88, 2, 'قوشچی', 'قوشچی', '0');
INSERT INTO `cities` VALUES (89, 2, 'کشاورز', 'کشاورز', '0');
INSERT INTO `cities` VALUES (90, 2, 'گردکشانه', 'گردکشانه', '0');
INSERT INTO `cities` VALUES (91, 2, 'ماکو', 'ماکو', '0');
INSERT INTO `cities` VALUES (92, 2, 'محمدیار', 'محمدیار', '0');
INSERT INTO `cities` VALUES (93, 2, 'محمودآباد', 'آذربایجان-غربی-محمودآباد', '0');
INSERT INTO `cities` VALUES (94, 2, 'مهاباد', 'آذربایجان-غربی-مهاباد', '0');
INSERT INTO `cities` VALUES (95, 2, 'میاندوآب', 'میاندوآب', '0');
INSERT INTO `cities` VALUES (96, 2, 'میرآباد', 'میرآباد', '0');
INSERT INTO `cities` VALUES (97, 2, 'نالوس', 'نالوس', '0');
INSERT INTO `cities` VALUES (98, 2, 'نقده', 'نقده', '0');
INSERT INTO `cities` VALUES (99, 2, 'نوشین', 'نوشین', '0');
INSERT INTO `cities` VALUES (100, 3, 'اردبیل', 'شهر-اردبیل', '0');
INSERT INTO `cities` VALUES (101, 3, 'اصلاندوز', 'اصلاندوز', '0');
INSERT INTO `cities` VALUES (102, 3, 'آبی بیگلو', 'آبی-بیگلو', '0');
INSERT INTO `cities` VALUES (103, 3, 'بیله سوار', 'بیله-سوار', '0');
INSERT INTO `cities` VALUES (104, 3, 'پارس آباد', 'پارس-آباد', '0');
INSERT INTO `cities` VALUES (105, 3, 'تازه کند', 'تازه-کند', '0');
INSERT INTO `cities` VALUES (106, 3, 'تازه کندانگوت', 'تازه-کندانگوت', '0');
INSERT INTO `cities` VALUES (107, 3, 'جعفرآباد', 'جعفرآباد', '0');
INSERT INTO `cities` VALUES (108, 3, 'خلخال', 'خلخال', '0');
INSERT INTO `cities` VALUES (109, 3, 'رضی', 'رضی', '0');
INSERT INTO `cities` VALUES (110, 3, 'سرعین', 'سرعین', '0');
INSERT INTO `cities` VALUES (111, 3, 'عنبران', 'عنبران', '0');
INSERT INTO `cities` VALUES (112, 3, 'فخرآباد', 'فخرآباد', '0');
INSERT INTO `cities` VALUES (113, 3, 'کلور', 'کلور', '0');
INSERT INTO `cities` VALUES (114, 3, 'کوراییم', 'کوراییم', '0');
INSERT INTO `cities` VALUES (115, 3, 'گرمی', 'گرمی', '0');
INSERT INTO `cities` VALUES (116, 3, 'گیوی', 'گیوی', '0');
INSERT INTO `cities` VALUES (117, 3, 'لاهرود', 'لاهرود', '0');
INSERT INTO `cities` VALUES (118, 3, 'مشگین شهر', 'مشگین-شهر', '0');
INSERT INTO `cities` VALUES (119, 3, 'نمین', 'نمین', '0');
INSERT INTO `cities` VALUES (120, 3, 'نیر', 'اردبیل-نیر', '0');
INSERT INTO `cities` VALUES (121, 3, 'هشتجین', 'هشتجین', '0');
INSERT INTO `cities` VALUES (122, 3, 'هیر', 'هیر', '0');
INSERT INTO `cities` VALUES (123, 4, 'ابریشم', 'ابریشم', '0');
INSERT INTO `cities` VALUES (124, 4, 'ابوزیدآباد', 'ابوزیدآباد', '0');
INSERT INTO `cities` VALUES (125, 4, 'اردستان', 'اردستان', '0');
INSERT INTO `cities` VALUES (126, 4, 'اژیه', 'اژیه', '0');
INSERT INTO `cities` VALUES (127, 4, 'اصفهان', 'شهر-اصفهان', '0');
INSERT INTO `cities` VALUES (128, 4, 'افوس', 'افوس', '0');
INSERT INTO `cities` VALUES (129, 4, 'انارک', 'انارک', '0');
INSERT INTO `cities` VALUES (130, 4, 'ایمانشهر', 'ایمانشهر', '0');
INSERT INTO `cities` VALUES (131, 4, 'آران وبیدگل', 'آران-وبیدگل', '0');
INSERT INTO `cities` VALUES (132, 4, 'بادرود', 'بادرود', '0');
INSERT INTO `cities` VALUES (133, 4, 'باغ بهادران', 'باغ-بهادران', '0');
INSERT INTO `cities` VALUES (134, 4, 'بافران', 'بافران', '0');
INSERT INTO `cities` VALUES (135, 4, 'برزک', 'برزک', '0');
INSERT INTO `cities` VALUES (136, 4, 'برف انبار', 'برف-انبار', '0');
INSERT INTO `cities` VALUES (137, 4, 'بهاران شهر', 'بهاران-شهر', '0');
INSERT INTO `cities` VALUES (138, 4, 'بهارستان', 'بهارستان', '0');
INSERT INTO `cities` VALUES (139, 4, 'بوئین و میاندشت', 'بوئین-میاندشت', '0');
INSERT INTO `cities` VALUES (140, 4, 'پیربکران', 'پیربکران', '0');
INSERT INTO `cities` VALUES (141, 4, 'تودشک', 'تودشک', '0');
INSERT INTO `cities` VALUES (142, 4, 'تیران', 'تیران', '0');
INSERT INTO `cities` VALUES (143, 4, 'جندق', 'جندق', '0');
INSERT INTO `cities` VALUES (144, 4, 'جوزدان', 'جوزدان', '0');
INSERT INTO `cities` VALUES (145, 4, 'جوشقان و کامو', 'جوشقان-کامو', '0');
INSERT INTO `cities` VALUES (146, 4, 'چادگان', 'چادگان', '0');
INSERT INTO `cities` VALUES (147, 4, 'چرمهین', 'چرمهین', '0');
INSERT INTO `cities` VALUES (148, 4, 'چمگردان', 'چمگردان', '0');
INSERT INTO `cities` VALUES (149, 4, 'حبیب آباد', 'حبیب-آباد', '0');
INSERT INTO `cities` VALUES (150, 4, 'حسن آباد', 'اصفهان-حسن-آباد', '0');
INSERT INTO `cities` VALUES (151, 4, 'حنا', 'حنا', '0');
INSERT INTO `cities` VALUES (152, 4, 'خالدآباد', 'خالدآباد', '0');
INSERT INTO `cities` VALUES (153, 4, 'خمینی شهر', 'خمینی-شهر', '0');
INSERT INTO `cities` VALUES (154, 4, 'خوانسار', 'خوانسار', '0');
INSERT INTO `cities` VALUES (155, 4, 'خور', 'اصفهان-خور', '0');
INSERT INTO `cities` VALUES (157, 4, 'خورزوق', 'خورزوق', '0');
INSERT INTO `cities` VALUES (158, 4, 'داران', 'داران', '0');
INSERT INTO `cities` VALUES (159, 4, 'دامنه', 'دامنه', '0');
INSERT INTO `cities` VALUES (160, 4, 'درچه', 'درچه', '0');
INSERT INTO `cities` VALUES (161, 4, 'دستگرد', 'دستگرد', '0');
INSERT INTO `cities` VALUES (162, 4, 'دهاقان', 'دهاقان', '0');
INSERT INTO `cities` VALUES (163, 4, 'دهق', 'دهق', '0');
INSERT INTO `cities` VALUES (164, 4, 'دولت آباد', 'اصفهان-دولت-آباد', '0');
INSERT INTO `cities` VALUES (165, 4, 'دیزیچه', 'دیزیچه', '0');
INSERT INTO `cities` VALUES (166, 4, 'رزوه', 'رزوه', '0');
INSERT INTO `cities` VALUES (167, 4, 'رضوانشهر', 'اصفهان-رضوانشهر', '0');
INSERT INTO `cities` VALUES (168, 4, 'زاینده رود', 'زاینده-رود', '0');
INSERT INTO `cities` VALUES (169, 4, 'زرین شهر', 'زرین-شهر', '0');
INSERT INTO `cities` VALUES (170, 4, 'زواره', 'زواره', '0');
INSERT INTO `cities` VALUES (171, 4, 'زیباشهر', 'زیباشهر', '0');
INSERT INTO `cities` VALUES (172, 4, 'سده لنجان', 'سده-لنجان', '0');
INSERT INTO `cities` VALUES (173, 4, 'سفیدشهر', 'سفیدشهر', '0');
INSERT INTO `cities` VALUES (174, 4, 'سگزی', 'سگزی', '0');
INSERT INTO `cities` VALUES (175, 4, 'سمیرم', 'سمیرم', '0');
INSERT INTO `cities` VALUES (176, 4, 'شاهین شهر', 'شاهین-شهر', '0');
INSERT INTO `cities` VALUES (177, 4, 'شهرضا', 'شهرضا', '0');
INSERT INTO `cities` VALUES (178, 4, 'طالخونچه', 'طالخونچه', '0');
INSERT INTO `cities` VALUES (179, 4, 'عسگران', 'عسگران', '0');
INSERT INTO `cities` VALUES (180, 4, 'علویجه', 'علویجه', '0');
INSERT INTO `cities` VALUES (181, 4, 'فرخی', 'فرخی', '0');
INSERT INTO `cities` VALUES (182, 4, 'فریدونشهر', 'فریدونشهر', '0');
INSERT INTO `cities` VALUES (183, 4, 'فلاورجان', 'فلاورجان', '0');
INSERT INTO `cities` VALUES (184, 4, 'فولادشهر', 'فولادشهر', '0');
INSERT INTO `cities` VALUES (185, 4, 'قمصر', 'قمصر', '0');
INSERT INTO `cities` VALUES (186, 4, 'قهجاورستان', 'قهجاورستان', '0');
INSERT INTO `cities` VALUES (187, 4, 'قهدریجان', 'قهدریجان', '0');
INSERT INTO `cities` VALUES (188, 4, 'کاشان', 'کاشان', '0');
INSERT INTO `cities` VALUES (189, 4, 'کرکوند', 'کرکوند', '0');
INSERT INTO `cities` VALUES (190, 4, 'کلیشاد و سودرجان', 'کلیشاد-سودرجان', '0');
INSERT INTO `cities` VALUES (191, 4, 'کمشچه', 'کمشچه', '0');
INSERT INTO `cities` VALUES (192, 4, 'کمه', 'کمه', '0');
INSERT INTO `cities` VALUES (193, 4, 'کهریزسنگ', 'کهریزسنگ', '0');
INSERT INTO `cities` VALUES (194, 4, 'کوشک', 'کوشک', '0');
INSERT INTO `cities` VALUES (195, 4, 'کوهپایه', 'کوهپایه', '0');
INSERT INTO `cities` VALUES (196, 4, 'گرگاب', 'گرگاب', '0');
INSERT INTO `cities` VALUES (197, 4, 'گزبرخوار', 'گزبرخوار', '0');
INSERT INTO `cities` VALUES (198, 4, 'گلپایگان', 'گلپایگان', '0');
INSERT INTO `cities` VALUES (199, 4, 'گلدشت', 'گلدشت', '0');
INSERT INTO `cities` VALUES (200, 4, 'گلشهر', 'گلشهر', '0');
INSERT INTO `cities` VALUES (201, 4, 'گوگد', 'گوگد', '0');
INSERT INTO `cities` VALUES (202, 4, 'لای بید', 'لای-بید', '0');
INSERT INTO `cities` VALUES (203, 4, 'مبارکه', 'مبارکه', '0');
INSERT INTO `cities` VALUES (204, 4, 'مجلسی', 'مجلسی', '0');
INSERT INTO `cities` VALUES (205, 4, 'محمدآباد', 'اصفهان-محمدآباد', '0');
INSERT INTO `cities` VALUES (206, 4, 'مشکات', 'مشکات', '0');
INSERT INTO `cities` VALUES (207, 4, 'منظریه', 'منظریه', '0');
INSERT INTO `cities` VALUES (208, 4, 'مهاباد', 'اصفهان-مهاباد', '0');
INSERT INTO `cities` VALUES (209, 4, 'میمه', 'اصفهان-میمه', '0');
INSERT INTO `cities` VALUES (210, 4, 'نائین', 'نائین', '0');
INSERT INTO `cities` VALUES (211, 4, 'نجف آباد', 'نجف-آباد', '0');
INSERT INTO `cities` VALUES (212, 4, 'نصرآباد', 'اصفهان-نصرآباد', '0');
INSERT INTO `cities` VALUES (213, 4, 'نطنز', 'نطنز', '0');
INSERT INTO `cities` VALUES (214, 4, 'نوش آباد', 'نوش-آباد', '0');
INSERT INTO `cities` VALUES (215, 4, 'نیاسر', 'نیاسر', '0');
INSERT INTO `cities` VALUES (216, 4, 'نیک آباد', 'نیک-آباد', '0');
INSERT INTO `cities` VALUES (217, 4, 'هرند', 'هرند', '0');
INSERT INTO `cities` VALUES (218, 4, 'ورزنه', 'ورزنه', '0');
INSERT INTO `cities` VALUES (219, 4, 'ورنامخواست', 'ورنامخواست', '0');
INSERT INTO `cities` VALUES (220, 4, 'وزوان', 'وزوان', '0');
INSERT INTO `cities` VALUES (221, 4, 'ونک', 'ونک', '0');
INSERT INTO `cities` VALUES (222, 5, 'اسارا', 'اسارا', '0');
INSERT INTO `cities` VALUES (223, 5, 'اشتهارد', 'اشتهارد', '0');
INSERT INTO `cities` VALUES (224, 5, 'تنکمان', 'تنکمان', '0');
INSERT INTO `cities` VALUES (225, 5, 'چهارباغ', 'چهارباغ', '0');
INSERT INTO `cities` VALUES (226, 5, 'سیف آباد', 'سیف-آباد', '0');
INSERT INTO `cities` VALUES (227, 5, 'شهر جدید هشتگرد', 'شهر-جدید-هشتگرد', '0');
INSERT INTO `cities` VALUES (228, 5, 'طالقان', 'طالقان', '0');
INSERT INTO `cities` VALUES (229, 5, 'کرج', 'کرج', '0');
INSERT INTO `cities` VALUES (230, 5, 'کمال شهر', 'کمال-شهر', '0');
INSERT INTO `cities` VALUES (231, 5, 'کوهسار', 'کوهسار', '0');
INSERT INTO `cities` VALUES (232, 5, 'گرمدره', 'گرمدره', '0');
INSERT INTO `cities` VALUES (233, 5, 'ماهدشت', 'ماهدشت', '0');
INSERT INTO `cities` VALUES (234, 5, 'محمدشهر', 'البرز-محمدشهر', '0');
INSERT INTO `cities` VALUES (235, 5, 'مشکین دشت', 'مشکین-دشت', '0');
INSERT INTO `cities` VALUES (236, 5, 'نظرآباد', 'نظرآباد', '0');
INSERT INTO `cities` VALUES (237, 5, 'هشتگرد', 'هشتگرد', '0');
INSERT INTO `cities` VALUES (238, 6, 'ارکواز', 'ارکواز', '0');
INSERT INTO `cities` VALUES (239, 6, 'ایلام', 'شهر-ایلام', '0');
INSERT INTO `cities` VALUES (240, 6, 'ایوان', 'ایوان', '0');
INSERT INTO `cities` VALUES (241, 6, 'آبدانان', 'آبدانان', '0');
INSERT INTO `cities` VALUES (242, 6, 'آسمان آباد', 'آسمان-آباد', '0');
INSERT INTO `cities` VALUES (243, 6, 'بدره', 'بدره', '0');
INSERT INTO `cities` VALUES (244, 6, 'پهله', 'پهله', '0');
INSERT INTO `cities` VALUES (245, 6, 'توحید', 'توحید', '0');
INSERT INTO `cities` VALUES (246, 6, 'چوار', 'چوار', '0');
INSERT INTO `cities` VALUES (247, 6, 'دره شهر', 'دره-شهر', '0');
INSERT INTO `cities` VALUES (248, 6, 'دلگشا', 'دلگشا', '0');
INSERT INTO `cities` VALUES (249, 6, 'دهلران', 'دهلران', '0');
INSERT INTO `cities` VALUES (250, 6, 'زرنه', 'زرنه', '0');
INSERT INTO `cities` VALUES (251, 6, 'سراب باغ', 'سراب-باغ', '0');
INSERT INTO `cities` VALUES (252, 6, 'سرابله', 'سرابله', '0');
INSERT INTO `cities` VALUES (253, 6, 'صالح آباد', 'ایلام-صالح-آباد', '0');
INSERT INTO `cities` VALUES (254, 6, 'لومار', 'لومار', '0');
INSERT INTO `cities` VALUES (255, 6, 'مهران', 'مهران', '0');
INSERT INTO `cities` VALUES (256, 6, 'مورموری', 'مورموری', '0');
INSERT INTO `cities` VALUES (257, 6, 'موسیان', 'موسیان', '0');
INSERT INTO `cities` VALUES (258, 6, 'میمه', 'ایلام-میمه', '0');
INSERT INTO `cities` VALUES (259, 7, 'امام حسن', 'امام-حسن', '0');
INSERT INTO `cities` VALUES (260, 7, 'انارستان', 'انارستان', '0');
INSERT INTO `cities` VALUES (261, 7, 'اهرم', 'اهرم', '0');
INSERT INTO `cities` VALUES (262, 7, 'آب پخش', 'آب-پخش', '0');
INSERT INTO `cities` VALUES (263, 7, 'آبدان', 'آبدان', '0');
INSERT INTO `cities` VALUES (264, 7, 'برازجان', 'برازجان', '0');
INSERT INTO `cities` VALUES (265, 7, 'بردخون', 'بردخون', '0');
INSERT INTO `cities` VALUES (266, 7, 'بندردیر', 'بندردیر', '0');
INSERT INTO `cities` VALUES (267, 7, 'بندردیلم', 'بندردیلم', '0');
INSERT INTO `cities` VALUES (268, 7, 'بندرریگ', 'بندرریگ', '0');
INSERT INTO `cities` VALUES (269, 7, 'بندرکنگان', 'بندرکنگان', '0');
INSERT INTO `cities` VALUES (270, 7, 'بندرگناوه', 'بندرگناوه', '0');
INSERT INTO `cities` VALUES (271, 7, 'بنک', 'بنک', '0');
INSERT INTO `cities` VALUES (272, 7, 'بوشهر', 'شهر-بوشهر', '0');
INSERT INTO `cities` VALUES (273, 7, 'تنگ ارم', 'تنگ-ارم', '0');
INSERT INTO `cities` VALUES (274, 7, 'جم', 'جم', '0');
INSERT INTO `cities` VALUES (275, 7, 'چغادک', 'چغادک', '0');
INSERT INTO `cities` VALUES (276, 7, 'خارک', 'خارک', '0');
INSERT INTO `cities` VALUES (277, 7, 'خورموج', 'خورموج', '0');
INSERT INTO `cities` VALUES (278, 7, 'دالکی', 'دالکی', '0');
INSERT INTO `cities` VALUES (279, 7, 'دلوار', 'دلوار', '0');
INSERT INTO `cities` VALUES (280, 7, 'ریز', 'ریز', '0');
INSERT INTO `cities` VALUES (281, 7, 'سعدآباد', 'سعدآباد', '0');
INSERT INTO `cities` VALUES (282, 7, 'سیراف', 'سیراف', '0');
INSERT INTO `cities` VALUES (283, 7, 'شبانکاره', 'شبانکاره', '0');
INSERT INTO `cities` VALUES (284, 7, 'شنبه', 'شنبه', '0');
INSERT INTO `cities` VALUES (285, 7, 'عسلویه', 'عسلویه', '0');
INSERT INTO `cities` VALUES (286, 7, 'کاکی', 'کاکی', '0');
INSERT INTO `cities` VALUES (287, 7, 'کلمه', 'کلمه', '0');
INSERT INTO `cities` VALUES (288, 7, 'نخل تقی', 'نخل-تقی', '0');
INSERT INTO `cities` VALUES (289, 7, 'وحدتیه', 'وحدتیه', '0');
INSERT INTO `cities` VALUES (290, 8, 'ارجمند', 'ارجمند', '0');
INSERT INTO `cities` VALUES (291, 8, 'اسلامشهر', 'اسلامشهر', '0');
INSERT INTO `cities` VALUES (292, 8, 'اندیشه', 'اندیشه', '0');
INSERT INTO `cities` VALUES (293, 8, 'آبسرد', 'آبسرد', '0');
INSERT INTO `cities` VALUES (294, 8, 'آبعلی', 'آبعلی', '0');
INSERT INTO `cities` VALUES (295, 8, 'باغستان', 'باغستان', '0');
INSERT INTO `cities` VALUES (296, 8, 'باقرشهر', 'باقرشهر', '0');
INSERT INTO `cities` VALUES (297, 8, 'بومهن', 'بومهن', '0');
INSERT INTO `cities` VALUES (298, 8, 'پاکدشت', 'پاکدشت', '0');
INSERT INTO `cities` VALUES (299, 8, 'پردیس', 'پردیس', '0');
INSERT INTO `cities` VALUES (300, 8, 'پیشوا', 'پیشوا', '0');
INSERT INTO `cities` VALUES (301, 8, 'تهران', 'شهر-تهران', '0');
INSERT INTO `cities` VALUES (302, 8, 'جوادآباد', 'جوادآباد', '0');
INSERT INTO `cities` VALUES (303, 8, 'چهاردانگه', 'چهاردانگه', '0');
INSERT INTO `cities` VALUES (304, 8, 'حسن آباد', 'تهران-حسن-آباد', '0');
INSERT INTO `cities` VALUES (305, 8, 'دماوند', 'دماوند', '0');
INSERT INTO `cities` VALUES (306, 8, 'دیزین', 'دیزین', '0');
INSERT INTO `cities` VALUES (307, 8, 'ری', 'ری', '0');
INSERT INTO `cities` VALUES (308, 8, 'رباط کریم', 'رباط-کریم', '0');
INSERT INTO `cities` VALUES (309, 8, 'رودهن', 'رودهن', '0');
INSERT INTO `cities` VALUES (310, 8, 'شاهدشهر', 'شاهدشهر', '0');
INSERT INTO `cities` VALUES (311, 8, 'شریف آباد', 'شریف-آباد', '0');
INSERT INTO `cities` VALUES (312, 8, 'شمشک', 'شمشک', '0');
INSERT INTO `cities` VALUES (313, 8, 'شهریار', 'شهریار', '0');
INSERT INTO `cities` VALUES (314, 8, 'صالح آباد', 'تهران-صالح-آباد', '0');
INSERT INTO `cities` VALUES (315, 8, 'صباشهر', 'صباشهر', '0');
INSERT INTO `cities` VALUES (316, 8, 'صفادشت', 'صفادشت', '0');
INSERT INTO `cities` VALUES (317, 8, 'فردوسیه', 'فردوسیه', '0');
INSERT INTO `cities` VALUES (318, 8, 'فشم', 'فشم', '0');
INSERT INTO `cities` VALUES (319, 8, 'فیروزکوه', 'فیروزکوه', '0');
INSERT INTO `cities` VALUES (320, 8, 'قدس', 'قدس', '0');
INSERT INTO `cities` VALUES (321, 8, 'قرچک', 'قرچک', '0');
INSERT INTO `cities` VALUES (322, 8, 'کهریزک', 'کهریزک', '0');
INSERT INTO `cities` VALUES (323, 8, 'کیلان', 'کیلان', '0');
INSERT INTO `cities` VALUES (324, 8, 'گلستان', 'شهر-گلستان', '0');
INSERT INTO `cities` VALUES (325, 8, 'لواسان', 'لواسان', '0');
INSERT INTO `cities` VALUES (326, 8, 'ملارد', 'ملارد', '0');
INSERT INTO `cities` VALUES (327, 8, 'میگون', 'میگون', '0');
INSERT INTO `cities` VALUES (328, 8, 'نسیم شهر', 'نسیم-شهر', '0');
INSERT INTO `cities` VALUES (329, 8, 'نصیرآباد', 'نصیرآباد', '0');
INSERT INTO `cities` VALUES (330, 8, 'وحیدیه', 'وحیدیه', '0');
INSERT INTO `cities` VALUES (331, 8, 'ورامین', 'ورامین', '0');
INSERT INTO `cities` VALUES (332, 9, 'اردل', 'اردل', '0');
INSERT INTO `cities` VALUES (333, 9, 'آلونی', 'آلونی', '0');
INSERT INTO `cities` VALUES (334, 9, 'باباحیدر', 'باباحیدر', '0');
INSERT INTO `cities` VALUES (335, 9, 'بروجن', 'بروجن', '0');
INSERT INTO `cities` VALUES (336, 9, 'بلداجی', 'بلداجی', '0');
INSERT INTO `cities` VALUES (337, 9, 'بن', 'بن', '0');
INSERT INTO `cities` VALUES (338, 9, 'جونقان', 'جونقان', '0');
INSERT INTO `cities` VALUES (339, 9, 'چلگرد', 'چلگرد', '0');
INSERT INTO `cities` VALUES (340, 9, 'سامان', 'سامان', '0');
INSERT INTO `cities` VALUES (341, 9, 'سفیددشت', 'سفیددشت', '0');
INSERT INTO `cities` VALUES (342, 9, 'سودجان', 'سودجان', '0');
INSERT INTO `cities` VALUES (343, 9, 'سورشجان', 'سورشجان', '0');
INSERT INTO `cities` VALUES (344, 9, 'شلمزار', 'شلمزار', '0');
INSERT INTO `cities` VALUES (345, 9, 'شهرکرد', 'شهرکرد', '0');
INSERT INTO `cities` VALUES (346, 9, 'طاقانک', 'طاقانک', '0');
INSERT INTO `cities` VALUES (347, 9, 'فارسان', 'فارسان', '0');
INSERT INTO `cities` VALUES (348, 9, 'فرادبنه', 'فرادبنه', '0');
INSERT INTO `cities` VALUES (349, 9, 'فرخ شهر', 'فرخ-شهر', '0');
INSERT INTO `cities` VALUES (350, 9, 'کیان', 'کیان', '0');
INSERT INTO `cities` VALUES (351, 9, 'گندمان', 'گندمان', '0');
INSERT INTO `cities` VALUES (352, 9, 'گهرو', 'گهرو', '0');
INSERT INTO `cities` VALUES (353, 9, 'لردگان', 'لردگان', '0');
INSERT INTO `cities` VALUES (354, 9, 'مال خلیفه', 'مال-خلیفه', '0');
INSERT INTO `cities` VALUES (355, 9, 'ناغان', 'ناغان', '0');
INSERT INTO `cities` VALUES (356, 9, 'نافچ', 'نافچ', '0');
INSERT INTO `cities` VALUES (357, 9, 'نقنه', 'نقنه', '0');
INSERT INTO `cities` VALUES (358, 9, 'هفشجان', 'هفشجان', '0');
INSERT INTO `cities` VALUES (359, 10, 'ارسک', 'ارسک', '0');
INSERT INTO `cities` VALUES (360, 10, 'اسدیه', 'اسدیه', '0');
INSERT INTO `cities` VALUES (361, 10, 'اسفدن', 'اسفدن', '0');
INSERT INTO `cities` VALUES (362, 10, 'اسلامیه', 'اسلامیه', '0');
INSERT INTO `cities` VALUES (363, 10, 'آرین شهر', 'آرین-شهر', '0');
INSERT INTO `cities` VALUES (364, 10, 'آیسک', 'آیسک', '0');
INSERT INTO `cities` VALUES (365, 10, 'بشرویه', 'بشرویه', '0');
INSERT INTO `cities` VALUES (366, 10, 'بیرجند', 'بیرجند', '0');
INSERT INTO `cities` VALUES (367, 10, 'حاجی آباد', 'خراسان-جنوبی-حاجی-آباد', '0');
INSERT INTO `cities` VALUES (368, 10, 'خضری دشت بیاض', 'خضری-دشت-بیاض', '0');
INSERT INTO `cities` VALUES (369, 10, 'خوسف', 'خوسف', '0');
INSERT INTO `cities` VALUES (370, 10, 'زهان', 'زهان', '0');
INSERT INTO `cities` VALUES (371, 10, 'سرایان', 'سرایان', '0');
INSERT INTO `cities` VALUES (372, 10, 'سربیشه', 'سربیشه', '0');
INSERT INTO `cities` VALUES (373, 10, 'سه قلعه', 'سه-قلعه', '0');
INSERT INTO `cities` VALUES (374, 10, 'شوسف', 'شوسف', '0');
INSERT INTO `cities` VALUES (375, 10, 'طبس ', 'خراسان-جنوبی-طبس-', '0');
INSERT INTO `cities` VALUES (376, 10, 'فردوس', 'فردوس', '0');
INSERT INTO `cities` VALUES (377, 10, 'قاین', 'قاین', '0');
INSERT INTO `cities` VALUES (378, 10, 'قهستان', 'قهستان', '0');
INSERT INTO `cities` VALUES (379, 10, 'محمدشهر', 'خراسان-جنوبی-محمدشهر', '0');
INSERT INTO `cities` VALUES (380, 10, 'مود', 'مود', '0');
INSERT INTO `cities` VALUES (381, 10, 'نهبندان', 'نهبندان', '0');
INSERT INTO `cities` VALUES (382, 10, 'نیمبلوک', 'نیمبلوک', '0');
INSERT INTO `cities` VALUES (383, 11, 'احمدآباد صولت', 'احمدآباد-صولت', '0');
INSERT INTO `cities` VALUES (384, 11, 'انابد', 'انابد', '0');
INSERT INTO `cities` VALUES (385, 11, 'باجگیران', 'باجگیران', '0');
INSERT INTO `cities` VALUES (386, 11, 'باخرز', 'باخرز', '0');
INSERT INTO `cities` VALUES (387, 11, 'بار', 'بار', '0');
INSERT INTO `cities` VALUES (388, 11, 'بایگ', 'بایگ', '0');
INSERT INTO `cities` VALUES (389, 11, 'بجستان', 'بجستان', '0');
INSERT INTO `cities` VALUES (390, 11, 'بردسکن', 'بردسکن', '0');
INSERT INTO `cities` VALUES (391, 11, 'بیدخت', 'بیدخت', '0');
INSERT INTO `cities` VALUES (392, 11, 'تایباد', 'تایباد', '0');
INSERT INTO `cities` VALUES (393, 11, 'تربت جام', 'تربت-جام', '0');
INSERT INTO `cities` VALUES (394, 11, 'تربت حیدریه', 'تربت-حیدریه', '0');
INSERT INTO `cities` VALUES (395, 11, 'جغتای', 'جغتای', '0');
INSERT INTO `cities` VALUES (396, 11, 'جنگل', 'جنگل', '0');
INSERT INTO `cities` VALUES (397, 11, 'چاپشلو', 'چاپشلو', '0');
INSERT INTO `cities` VALUES (398, 11, 'چکنه', 'چکنه', '0');
INSERT INTO `cities` VALUES (399, 11, 'چناران', 'چناران', '0');
INSERT INTO `cities` VALUES (400, 11, 'خرو', 'خرو', '0');
INSERT INTO `cities` VALUES (401, 11, 'خلیل آباد', 'خلیل-آباد', '0');
INSERT INTO `cities` VALUES (402, 11, 'خواف', 'خواف', '0');
INSERT INTO `cities` VALUES (403, 11, 'داورزن', 'داورزن', '0');
INSERT INTO `cities` VALUES (404, 11, 'درگز', 'درگز', '0');
INSERT INTO `cities` VALUES (405, 11, 'در رود', 'در-رود', '0');
INSERT INTO `cities` VALUES (406, 11, 'دولت آباد', 'خراسان-رضوی-دولت-آباد', '0');
INSERT INTO `cities` VALUES (407, 11, 'رباط سنگ', 'رباط-سنگ', '0');
INSERT INTO `cities` VALUES (408, 11, 'رشتخوار', 'رشتخوار', '0');
INSERT INTO `cities` VALUES (409, 11, 'رضویه', 'رضویه', '0');
INSERT INTO `cities` VALUES (410, 11, 'روداب', 'روداب', '0');
INSERT INTO `cities` VALUES (411, 11, 'ریوش', 'ریوش', '0');
INSERT INTO `cities` VALUES (412, 11, 'سبزوار', 'سبزوار', '0');
INSERT INTO `cities` VALUES (413, 11, 'سرخس', 'سرخس', '0');
INSERT INTO `cities` VALUES (414, 11, 'سفیدسنگ', 'سفیدسنگ', '0');
INSERT INTO `cities` VALUES (415, 11, 'سلامی', 'سلامی', '0');
INSERT INTO `cities` VALUES (416, 11, 'سلطان آباد', 'سلطان-آباد', '0');
INSERT INTO `cities` VALUES (417, 11, 'سنگان', 'سنگان', '0');
INSERT INTO `cities` VALUES (418, 11, 'شادمهر', 'شادمهر', '0');
INSERT INTO `cities` VALUES (419, 11, 'شاندیز', 'شاندیز', '0');
INSERT INTO `cities` VALUES (420, 11, 'ششتمد', 'ششتمد', '0');
INSERT INTO `cities` VALUES (421, 11, 'شهرآباد', 'شهرآباد', '0');
INSERT INTO `cities` VALUES (422, 11, 'شهرزو', 'شهرزو', '0');
INSERT INTO `cities` VALUES (423, 11, 'صالح آباد', 'خراسان-رضوی-صالح-آباد', '0');
INSERT INTO `cities` VALUES (424, 11, 'طرقبه', 'طرقبه', '0');
INSERT INTO `cities` VALUES (425, 11, 'عشق آباد', 'خراسان-رضوی-عشق-آباد', '0');
INSERT INTO `cities` VALUES (426, 11, 'فرهادگرد', 'فرهادگرد', '0');
INSERT INTO `cities` VALUES (427, 11, 'فریمان', 'فریمان', '0');
INSERT INTO `cities` VALUES (428, 11, 'فیروزه', 'فیروزه', '0');
INSERT INTO `cities` VALUES (429, 11, 'فیض آباد', 'فیض-آباد', '0');
INSERT INTO `cities` VALUES (430, 11, 'قاسم آباد', 'قاسم-آباد', '0');
INSERT INTO `cities` VALUES (431, 11, 'قدمگاه', 'قدمگاه', '0');
INSERT INTO `cities` VALUES (432, 11, 'قلندرآباد', 'قلندرآباد', '0');
INSERT INTO `cities` VALUES (433, 11, 'قوچان', 'قوچان', '0');
INSERT INTO `cities` VALUES (434, 11, 'کاخک', 'کاخک', '0');
INSERT INTO `cities` VALUES (435, 11, 'کاریز', 'کاریز', '0');
INSERT INTO `cities` VALUES (436, 11, 'کاشمر', 'کاشمر', '0');
INSERT INTO `cities` VALUES (437, 11, 'کدکن', 'کدکن', '0');
INSERT INTO `cities` VALUES (438, 11, 'کلات', 'کلات', '0');
INSERT INTO `cities` VALUES (439, 11, 'کندر', 'کندر', '0');
INSERT INTO `cities` VALUES (440, 11, 'گلمکان', 'گلمکان', '0');
INSERT INTO `cities` VALUES (441, 11, 'گناباد', 'گناباد', '0');
INSERT INTO `cities` VALUES (442, 11, 'لطف آباد', 'لطف-آباد', '0');
INSERT INTO `cities` VALUES (443, 11, 'مزدآوند', 'مزدآوند', '0');
INSERT INTO `cities` VALUES (444, 11, 'مشهد', 'مشهد', '0');
INSERT INTO `cities` VALUES (445, 11, 'ملک آباد', 'ملک-آباد', '0');
INSERT INTO `cities` VALUES (446, 11, 'نشتیفان', 'نشتیفان', '0');
INSERT INTO `cities` VALUES (447, 11, 'نصرآباد', 'خراسان-رضوی-نصرآباد', '0');
INSERT INTO `cities` VALUES (448, 11, 'نقاب', 'نقاب', '0');
INSERT INTO `cities` VALUES (449, 11, 'نوخندان', 'نوخندان', '0');
INSERT INTO `cities` VALUES (450, 11, 'نیشابور', 'نیشابور', '0');
INSERT INTO `cities` VALUES (451, 11, 'نیل شهر', 'نیل-شهر', '0');
INSERT INTO `cities` VALUES (452, 11, 'همت آباد', 'همت-آباد', '0');
INSERT INTO `cities` VALUES (453, 11, 'یونسی', 'یونسی', '0');
INSERT INTO `cities` VALUES (454, 12, 'اسفراین', 'اسفراین', '0');
INSERT INTO `cities` VALUES (455, 12, 'ایور', 'ایور', '0');
INSERT INTO `cities` VALUES (456, 12, 'آشخانه', 'آشخانه', '0');
INSERT INTO `cities` VALUES (457, 12, 'بجنورد', 'بجنورد', '0');
INSERT INTO `cities` VALUES (458, 12, 'پیش قلعه', 'پیش-قلعه', '0');
INSERT INTO `cities` VALUES (459, 12, 'تیتکانلو', 'تیتکانلو', '0');
INSERT INTO `cities` VALUES (460, 12, 'جاجرم', 'جاجرم', '0');
INSERT INTO `cities` VALUES (461, 12, 'حصارگرمخان', 'حصارگرمخان', '0');
INSERT INTO `cities` VALUES (462, 12, 'درق', 'درق', '0');
INSERT INTO `cities` VALUES (463, 12, 'راز', 'راز', '0');
INSERT INTO `cities` VALUES (464, 12, 'سنخواست', 'سنخواست', '0');
INSERT INTO `cities` VALUES (465, 12, 'شوقان', 'شوقان', '0');
INSERT INTO `cities` VALUES (466, 12, 'شیروان', 'شیروان', '0');
INSERT INTO `cities` VALUES (467, 12, 'صفی آباد', 'خراسان-شمالی-صفی-آباد', '0');
INSERT INTO `cities` VALUES (468, 12, 'فاروج', 'فاروج', '0');
INSERT INTO `cities` VALUES (469, 12, 'قاضی', 'قاضی', '0');
INSERT INTO `cities` VALUES (470, 12, 'گرمه', 'گرمه', '0');
INSERT INTO `cities` VALUES (471, 12, 'لوجلی', 'لوجلی', '0');
INSERT INTO `cities` VALUES (472, 13, 'اروندکنار', 'اروندکنار', '0');
INSERT INTO `cities` VALUES (473, 13, 'الوان', 'الوان', '0');
INSERT INTO `cities` VALUES (474, 13, 'امیدیه', 'امیدیه', '0');
INSERT INTO `cities` VALUES (475, 13, 'اندیمشک', 'اندیمشک', '0');
INSERT INTO `cities` VALUES (476, 13, 'اهواز', 'اهواز', '0');
INSERT INTO `cities` VALUES (477, 13, 'ایذه', 'ایذه', '0');
INSERT INTO `cities` VALUES (478, 13, 'آبادان', 'آبادان', '0');
INSERT INTO `cities` VALUES (479, 13, 'آغاجاری', 'آغاجاری', '0');
INSERT INTO `cities` VALUES (480, 13, 'باغ ملک', 'باغ-ملک', '0');
INSERT INTO `cities` VALUES (481, 13, 'بستان', 'بستان', '0');
INSERT INTO `cities` VALUES (482, 13, 'بندرامام خمینی', 'بندرامام-خمینی', '0');
INSERT INTO `cities` VALUES (483, 13, 'بندرماهشهر', 'بندرماهشهر', '0');
INSERT INTO `cities` VALUES (484, 13, 'بهبهان', 'بهبهان', '0');
INSERT INTO `cities` VALUES (485, 13, 'ترکالکی', 'ترکالکی', '0');
INSERT INTO `cities` VALUES (486, 13, 'جایزان', 'جایزان', '0');
INSERT INTO `cities` VALUES (487, 13, 'چمران', 'چمران', '0');
INSERT INTO `cities` VALUES (488, 13, 'چویبده', 'چویبده', '0');
INSERT INTO `cities` VALUES (489, 13, 'حر', 'حر', '0');
INSERT INTO `cities` VALUES (490, 13, 'حسینیه', 'حسینیه', '0');
INSERT INTO `cities` VALUES (491, 13, 'حمزه', 'حمزه', '0');
INSERT INTO `cities` VALUES (492, 13, 'حمیدیه', 'حمیدیه', '0');
INSERT INTO `cities` VALUES (493, 13, 'خرمشهر', 'خرمشهر', '0');
INSERT INTO `cities` VALUES (494, 13, 'دارخوین', 'دارخوین', '0');
INSERT INTO `cities` VALUES (495, 13, 'دزآب', 'دزآب', '0');
INSERT INTO `cities` VALUES (496, 13, 'دزفول', 'دزفول', '0');
INSERT INTO `cities` VALUES (497, 13, 'دهدز', 'دهدز', '0');
INSERT INTO `cities` VALUES (498, 13, 'رامشیر', 'رامشیر', '0');
INSERT INTO `cities` VALUES (499, 13, 'رامهرمز', 'رامهرمز', '0');
INSERT INTO `cities` VALUES (500, 13, 'رفیع', 'رفیع', '0');
INSERT INTO `cities` VALUES (501, 13, 'زهره', 'زهره', '0');
INSERT INTO `cities` VALUES (502, 13, 'سالند', 'سالند', '0');
INSERT INTO `cities` VALUES (503, 13, 'سردشت', 'خوزستان-سردشت', '0');
INSERT INTO `cities` VALUES (504, 13, 'سوسنگرد', 'سوسنگرد', '0');
INSERT INTO `cities` VALUES (505, 13, 'شادگان', 'شادگان', '0');
INSERT INTO `cities` VALUES (506, 13, 'شاوور', 'شاوور', '0');
INSERT INTO `cities` VALUES (507, 13, 'شرافت', 'شرافت', '0');
INSERT INTO `cities` VALUES (508, 13, 'شوش', 'شوش', '0');
INSERT INTO `cities` VALUES (509, 13, 'شوشتر', 'شوشتر', '0');
INSERT INTO `cities` VALUES (510, 13, 'شیبان', 'شیبان', '0');
INSERT INTO `cities` VALUES (511, 13, 'صالح شهر', 'صالح-شهر', '0');
INSERT INTO `cities` VALUES (512, 13, 'صفی آباد', 'خوزستان-صفی-آباد', '0');
INSERT INTO `cities` VALUES (513, 13, 'صیدون', 'صیدون', '0');
INSERT INTO `cities` VALUES (514, 13, 'قلعه تل', 'قلعه-تل', '0');
INSERT INTO `cities` VALUES (515, 13, 'قلعه خواجه', 'قلعه-خواجه', '0');
INSERT INTO `cities` VALUES (516, 13, 'گتوند', 'گتوند', '0');
INSERT INTO `cities` VALUES (517, 13, 'لالی', 'لالی', '0');
INSERT INTO `cities` VALUES (518, 13, 'مسجدسلیمان', 'مسجدسلیمان', '0');
INSERT INTO `cities` VALUES (520, 13, 'ملاثانی', 'ملاثانی', '0');
INSERT INTO `cities` VALUES (521, 13, 'میانرود', 'میانرود', '0');
INSERT INTO `cities` VALUES (522, 13, 'مینوشهر', 'مینوشهر', '0');
INSERT INTO `cities` VALUES (523, 13, 'هفتگل', 'هفتگل', '0');
INSERT INTO `cities` VALUES (524, 13, 'هندیجان', 'هندیجان', '0');
INSERT INTO `cities` VALUES (525, 13, 'هویزه', 'هویزه', '0');
INSERT INTO `cities` VALUES (526, 13, 'ویس', 'ویس', '0');
INSERT INTO `cities` VALUES (527, 14, 'ابهر', 'ابهر', '0');
INSERT INTO `cities` VALUES (528, 14, 'ارمغان خانه', 'ارمغان-خانه', '0');
INSERT INTO `cities` VALUES (529, 14, 'آب بر', 'آب-بر', '0');
INSERT INTO `cities` VALUES (530, 14, 'چورزق', 'چورزق', '0');
INSERT INTO `cities` VALUES (531, 14, 'حلب', 'حلب', '0');
INSERT INTO `cities` VALUES (532, 14, 'خرمدره', 'خرمدره', '0');
INSERT INTO `cities` VALUES (533, 14, 'دندی', 'دندی', '0');
INSERT INTO `cities` VALUES (534, 14, 'زرین آباد', 'زرین-آباد', '0');
INSERT INTO `cities` VALUES (535, 14, 'زرین رود', 'زرین-رود', '0');
INSERT INTO `cities` VALUES (536, 14, 'زنجان', 'شهر-زنجان', '0');
INSERT INTO `cities` VALUES (537, 14, 'سجاس', 'سجاس', '0');
INSERT INTO `cities` VALUES (538, 14, 'سلطانیه', 'سلطانیه', '0');
INSERT INTO `cities` VALUES (539, 14, 'سهرورد', 'سهرورد', '0');
INSERT INTO `cities` VALUES (540, 14, 'صائین قلعه', 'صائین-قلعه', '0');
INSERT INTO `cities` VALUES (541, 14, 'قیدار', 'قیدار', '0');
INSERT INTO `cities` VALUES (542, 14, 'گرماب', 'گرماب', '0');
INSERT INTO `cities` VALUES (543, 14, 'ماه نشان', 'ماه-نشان', '0');
INSERT INTO `cities` VALUES (544, 14, 'هیدج', 'هیدج', '0');
INSERT INTO `cities` VALUES (545, 15, 'امیریه', 'امیریه', '0');
INSERT INTO `cities` VALUES (546, 15, 'ایوانکی', 'ایوانکی', '0');
INSERT INTO `cities` VALUES (547, 15, 'آرادان', 'آرادان', '0');
INSERT INTO `cities` VALUES (548, 15, 'بسطام', 'بسطام', '0');
INSERT INTO `cities` VALUES (549, 15, 'بیارجمند', 'بیارجمند', '0');
INSERT INTO `cities` VALUES (550, 15, 'دامغان', 'دامغان', '0');
INSERT INTO `cities` VALUES (551, 15, 'درجزین', 'درجزین', '0');
INSERT INTO `cities` VALUES (552, 15, 'دیباج', 'دیباج', '0');
INSERT INTO `cities` VALUES (553, 15, 'سرخه', 'سرخه', '0');
INSERT INTO `cities` VALUES (554, 15, 'سمنان', 'شهر-سمنان', '0');
INSERT INTO `cities` VALUES (555, 15, 'شاهرود', 'شاهرود', '0');
INSERT INTO `cities` VALUES (556, 15, 'شهمیرزاد', 'شهمیرزاد', '0');
INSERT INTO `cities` VALUES (557, 15, 'کلاته خیج', 'کلاته-خیج', '0');
INSERT INTO `cities` VALUES (558, 15, 'گرمسار', 'گرمسار', '0');
INSERT INTO `cities` VALUES (559, 15, 'مجن', 'مجن', '0');
INSERT INTO `cities` VALUES (560, 15, 'مهدی شهر', 'مهدی-شهر', '0');
INSERT INTO `cities` VALUES (561, 15, 'میامی', 'میامی', '0');
INSERT INTO `cities` VALUES (562, 16, 'ادیمی', 'ادیمی', '0');
INSERT INTO `cities` VALUES (563, 16, 'اسپکه', 'اسپکه', '0');
INSERT INTO `cities` VALUES (564, 16, 'ایرانشهر', 'ایرانشهر', '0');
INSERT INTO `cities` VALUES (565, 16, 'بزمان', 'بزمان', '0');
INSERT INTO `cities` VALUES (566, 16, 'بمپور', 'بمپور', '0');
INSERT INTO `cities` VALUES (567, 16, 'بنت', 'بنت', '0');
INSERT INTO `cities` VALUES (568, 16, 'بنجار', 'بنجار', '0');
INSERT INTO `cities` VALUES (569, 16, 'پیشین', 'پیشین', '0');
INSERT INTO `cities` VALUES (570, 16, 'جالق', 'جالق', '0');
INSERT INTO `cities` VALUES (571, 16, 'چابهار', 'چابهار', '0');
INSERT INTO `cities` VALUES (572, 16, 'خاش', 'خاش', '0');
INSERT INTO `cities` VALUES (573, 16, 'دوست محمد', 'دوست-محمد', '0');
INSERT INTO `cities` VALUES (574, 16, 'راسک', 'راسک', '0');
INSERT INTO `cities` VALUES (575, 16, 'زابل', 'زابل', '0');
INSERT INTO `cities` VALUES (576, 16, 'زابلی', 'زابلی', '0');
INSERT INTO `cities` VALUES (577, 16, 'زاهدان', 'زاهدان', '0');
INSERT INTO `cities` VALUES (578, 16, 'زهک', 'زهک', '0');
INSERT INTO `cities` VALUES (579, 16, 'سراوان', 'سراوان', '0');
INSERT INTO `cities` VALUES (580, 16, 'سرباز', 'سرباز', '0');
INSERT INTO `cities` VALUES (581, 16, 'سوران', 'سوران', '0');
INSERT INTO `cities` VALUES (582, 16, 'سیرکان', 'سیرکان', '0');
INSERT INTO `cities` VALUES (583, 16, 'علی اکبر', 'علی-اکبر', '0');
INSERT INTO `cities` VALUES (584, 16, 'فنوج', 'فنوج', '0');
INSERT INTO `cities` VALUES (585, 16, 'قصرقند', 'قصرقند', '0');
INSERT INTO `cities` VALUES (586, 16, 'کنارک', 'کنارک', '0');
INSERT INTO `cities` VALUES (587, 16, 'گشت', 'گشت', '0');
INSERT INTO `cities` VALUES (588, 16, 'گلمورتی', 'گلمورتی', '0');
INSERT INTO `cities` VALUES (589, 16, 'محمدان', 'محمدان', '0');
INSERT INTO `cities` VALUES (590, 16, 'محمدآباد', 'سیستان-و-بلوچستان-محمدآباد', '0');
INSERT INTO `cities` VALUES (591, 16, 'محمدی', 'محمدی', '0');
INSERT INTO `cities` VALUES (592, 16, 'میرجاوه', 'میرجاوه', '0');
INSERT INTO `cities` VALUES (593, 16, 'نصرت آباد', 'نصرت-آباد', '0');
INSERT INTO `cities` VALUES (594, 16, 'نگور', 'نگور', '0');
INSERT INTO `cities` VALUES (595, 16, 'نوک آباد', 'نوک-آباد', '0');
INSERT INTO `cities` VALUES (596, 16, 'نیک شهر', 'نیک-شهر', '0');
INSERT INTO `cities` VALUES (597, 16, 'هیدوچ', 'هیدوچ', '0');
INSERT INTO `cities` VALUES (598, 17, 'اردکان', 'فارس-اردکان', '0');
INSERT INTO `cities` VALUES (599, 17, 'ارسنجان', 'ارسنجان', '0');
INSERT INTO `cities` VALUES (600, 17, 'استهبان', 'استهبان', '0');
INSERT INTO `cities` VALUES (601, 17, 'اشکنان', 'اشکنان', '0');
INSERT INTO `cities` VALUES (602, 17, 'افزر', 'افزر', '0');
INSERT INTO `cities` VALUES (603, 17, 'اقلید', 'اقلید', '0');
INSERT INTO `cities` VALUES (604, 17, 'امام شهر', 'امام-شهر', '0');
INSERT INTO `cities` VALUES (605, 17, 'اهل', 'اهل', '0');
INSERT INTO `cities` VALUES (606, 17, 'اوز', 'اوز', '0');
INSERT INTO `cities` VALUES (607, 17, 'ایج', 'ایج', '0');
INSERT INTO `cities` VALUES (608, 17, 'ایزدخواست', 'ایزدخواست', '0');
INSERT INTO `cities` VALUES (609, 17, 'آباده', 'آباده', '0');
INSERT INTO `cities` VALUES (610, 17, 'آباده طشک', 'آباده-طشک', '0');
INSERT INTO `cities` VALUES (611, 17, 'باب انار', 'باب-انار', '0');
INSERT INTO `cities` VALUES (612, 17, 'بالاده', 'فارس-بالاده', '0');
INSERT INTO `cities` VALUES (613, 17, 'بنارویه', 'بنارویه', '0');
INSERT INTO `cities` VALUES (614, 17, 'بهمن', 'بهمن', '0');
INSERT INTO `cities` VALUES (615, 17, 'بوانات', 'بوانات', '0');
INSERT INTO `cities` VALUES (616, 17, 'بیرم', 'بیرم', '0');
INSERT INTO `cities` VALUES (617, 17, 'بیضا', 'بیضا', '0');
INSERT INTO `cities` VALUES (618, 17, 'جنت شهر', 'جنت-شهر', '0');
INSERT INTO `cities` VALUES (619, 17, 'جهرم', 'جهرم', '0');
INSERT INTO `cities` VALUES (620, 17, 'جویم', 'جویم', '0');
INSERT INTO `cities` VALUES (621, 17, 'زرین دشت', 'زرین-دشت', '0');
INSERT INTO `cities` VALUES (622, 17, 'حسن آباد', 'فارس-حسن-آباد', '0');
INSERT INTO `cities` VALUES (623, 17, 'خان زنیان', 'خان-زنیان', '0');
INSERT INTO `cities` VALUES (624, 17, 'خاوران', 'خاوران', '0');
INSERT INTO `cities` VALUES (625, 17, 'خرامه', 'خرامه', '0');
INSERT INTO `cities` VALUES (626, 17, 'خشت', 'خشت', '0');
INSERT INTO `cities` VALUES (627, 17, 'خنج', 'خنج', '0');
INSERT INTO `cities` VALUES (628, 17, 'خور', 'فارس-خور', '0');
INSERT INTO `cities` VALUES (629, 17, 'داراب', 'داراب', '0');
INSERT INTO `cities` VALUES (630, 17, 'داریان', 'داریان', '0');
INSERT INTO `cities` VALUES (631, 17, 'دبیران', 'دبیران', '0');
INSERT INTO `cities` VALUES (632, 17, 'دژکرد', 'دژکرد', '0');
INSERT INTO `cities` VALUES (633, 17, 'دهرم', 'دهرم', '0');
INSERT INTO `cities` VALUES (634, 17, 'دوبرجی', 'دوبرجی', '0');
INSERT INTO `cities` VALUES (635, 17, 'رامجرد', 'رامجرد', '0');
INSERT INTO `cities` VALUES (636, 17, 'رونیز', 'رونیز', '0');
INSERT INTO `cities` VALUES (637, 17, 'زاهدشهر', 'زاهدشهر', '0');
INSERT INTO `cities` VALUES (638, 17, 'زرقان', 'زرقان', '0');
INSERT INTO `cities` VALUES (639, 17, 'سده', 'سده', '0');
INSERT INTO `cities` VALUES (640, 17, 'سروستان', 'سروستان', '0');
INSERT INTO `cities` VALUES (641, 17, 'سعادت شهر', 'سعادت-شهر', '0');
INSERT INTO `cities` VALUES (642, 17, 'سورمق', 'سورمق', '0');
INSERT INTO `cities` VALUES (643, 17, 'سیدان', 'سیدان', '0');
INSERT INTO `cities` VALUES (644, 17, 'ششده', 'ششده', '0');
INSERT INTO `cities` VALUES (645, 17, 'شهرپیر', 'شهرپیر', '0');
INSERT INTO `cities` VALUES (646, 17, 'شهرصدرا', 'شهرصدرا', '0');
INSERT INTO `cities` VALUES (647, 17, 'شیراز', 'شیراز', '0');
INSERT INTO `cities` VALUES (648, 17, 'صغاد', 'صغاد', '0');
INSERT INTO `cities` VALUES (649, 17, 'صفاشهر', 'صفاشهر', '0');
INSERT INTO `cities` VALUES (650, 17, 'علامرودشت', 'علامرودشت', '0');
INSERT INTO `cities` VALUES (651, 17, 'فدامی', 'فدامی', '0');
INSERT INTO `cities` VALUES (652, 17, 'فراشبند', 'فراشبند', '0');
INSERT INTO `cities` VALUES (653, 17, 'فسا', 'فسا', '0');
INSERT INTO `cities` VALUES (654, 17, 'فیروزآباد', 'فارس-فیروزآباد', '0');
INSERT INTO `cities` VALUES (655, 17, 'قائمیه', 'قائمیه', '0');
INSERT INTO `cities` VALUES (656, 17, 'قادرآباد', 'قادرآباد', '0');
INSERT INTO `cities` VALUES (657, 17, 'قطب آباد', 'قطب-آباد', '0');
INSERT INTO `cities` VALUES (658, 17, 'قطرویه', 'قطرویه', '0');
INSERT INTO `cities` VALUES (659, 17, 'قیر', 'قیر', '0');
INSERT INTO `cities` VALUES (660, 17, 'کارزین (فتح آباد)', 'کارزین-فتح-آباد', '0');
INSERT INTO `cities` VALUES (661, 17, 'کازرون', 'کازرون', '0');
INSERT INTO `cities` VALUES (662, 17, 'کامفیروز', 'کامفیروز', '0');
INSERT INTO `cities` VALUES (663, 17, 'کره ای', 'کره-ای', '0');
INSERT INTO `cities` VALUES (664, 17, 'کنارتخته', 'کنارتخته', '0');
INSERT INTO `cities` VALUES (665, 17, 'کوار', 'کوار', '0');
INSERT INTO `cities` VALUES (666, 17, 'گراش', 'گراش', '0');
INSERT INTO `cities` VALUES (667, 17, 'گله دار', 'گله-دار', '0');
INSERT INTO `cities` VALUES (668, 17, 'لار', 'لار', '0');
INSERT INTO `cities` VALUES (669, 17, 'لامرد', 'لامرد', '0');
INSERT INTO `cities` VALUES (670, 17, 'لپویی', 'لپویی', '0');
INSERT INTO `cities` VALUES (671, 17, 'لطیفی', 'لطیفی', '0');
INSERT INTO `cities` VALUES (672, 17, 'مبارک آباددیز', 'مبارک-آباددیز', '0');
INSERT INTO `cities` VALUES (673, 17, 'مرودشت', 'مرودشت', '0');
INSERT INTO `cities` VALUES (674, 17, 'مشکان', 'مشکان', '0');
INSERT INTO `cities` VALUES (675, 17, 'مصیری', 'مصیری', '0');
INSERT INTO `cities` VALUES (676, 17, 'مهر', 'مهر', '0');
INSERT INTO `cities` VALUES (677, 17, 'میمند', 'میمند', '0');
INSERT INTO `cities` VALUES (678, 17, 'نوبندگان', 'نوبندگان', '0');
INSERT INTO `cities` VALUES (679, 17, 'نوجین', 'نوجین', '0');
INSERT INTO `cities` VALUES (680, 17, 'نودان', 'نودان', '0');
INSERT INTO `cities` VALUES (681, 17, 'نورآباد', 'فارس-نورآباد', '0');
INSERT INTO `cities` VALUES (682, 17, 'نی ریز', 'نی-ریز', '0');
INSERT INTO `cities` VALUES (683, 17, 'وراوی', 'وراوی', '0');
INSERT INTO `cities` VALUES (684, 18, 'ارداق', 'ارداق', '0');
INSERT INTO `cities` VALUES (685, 18, 'اسفرورین', 'اسفرورین', '0');
INSERT INTO `cities` VALUES (686, 18, 'اقبالیه', 'اقبالیه', '0');
INSERT INTO `cities` VALUES (687, 18, 'الوند', 'الوند', '0');
INSERT INTO `cities` VALUES (688, 18, 'آبگرم', 'آبگرم', '0');
INSERT INTO `cities` VALUES (689, 18, 'آبیک', 'آبیک', '0');
INSERT INTO `cities` VALUES (690, 18, 'آوج', 'آوج', '0');
INSERT INTO `cities` VALUES (691, 18, 'بوئین زهرا', 'بوئین-زهرا', '0');
INSERT INTO `cities` VALUES (692, 18, 'بیدستان', 'بیدستان', '0');
INSERT INTO `cities` VALUES (693, 18, 'تاکستان', 'تاکستان', '0');
INSERT INTO `cities` VALUES (694, 18, 'خاکعلی', 'خاکعلی', '0');
INSERT INTO `cities` VALUES (695, 18, 'خرمدشت', 'خرمدشت', '0');
INSERT INTO `cities` VALUES (696, 18, 'دانسفهان', 'دانسفهان', '0');
INSERT INTO `cities` VALUES (697, 18, 'رازمیان', 'رازمیان', '0');
INSERT INTO `cities` VALUES (698, 18, 'سگزآباد', 'سگزآباد', '0');
INSERT INTO `cities` VALUES (699, 18, 'سیردان', 'سیردان', '0');
INSERT INTO `cities` VALUES (700, 18, 'شال', 'شال', '0');
INSERT INTO `cities` VALUES (701, 18, 'شریفیه', 'شریفیه', '0');
INSERT INTO `cities` VALUES (702, 18, 'ضیاآباد', 'ضیاآباد', '0');
INSERT INTO `cities` VALUES (703, 18, 'قزوین', 'شهر-قزوین', '0');
INSERT INTO `cities` VALUES (704, 18, 'کوهین', 'کوهین', '0');
INSERT INTO `cities` VALUES (705, 18, 'محمدیه', 'محمدیه', '0');
INSERT INTO `cities` VALUES (706, 18, 'محمودآباد نمونه', 'محمودآباد-نمونه', '0');
INSERT INTO `cities` VALUES (707, 18, 'معلم کلایه', 'معلم-کلایه', '0');
INSERT INTO `cities` VALUES (708, 18, 'نرجه', 'نرجه', '0');
INSERT INTO `cities` VALUES (709, 19, 'جعفریه', 'جعفریه', '0');
INSERT INTO `cities` VALUES (710, 19, 'دستجرد', 'دستجرد', '0');
INSERT INTO `cities` VALUES (711, 19, 'سلفچگان', 'سلفچگان', '0');
INSERT INTO `cities` VALUES (712, 19, 'قم', 'شهر-قم', '0');
INSERT INTO `cities` VALUES (713, 19, 'قنوات', 'قنوات', '0');
INSERT INTO `cities` VALUES (714, 19, 'کهک', 'کهک', '0');
INSERT INTO `cities` VALUES (715, 20, 'آرمرده', 'آرمرده', '0');
INSERT INTO `cities` VALUES (716, 20, 'بابارشانی', 'بابارشانی', '0');
INSERT INTO `cities` VALUES (717, 20, 'بانه', 'بانه', '0');
INSERT INTO `cities` VALUES (718, 20, 'بلبان آباد', 'بلبان-آباد', '0');
INSERT INTO `cities` VALUES (719, 20, 'بوئین سفلی', 'بوئین-سفلی', '0');
INSERT INTO `cities` VALUES (720, 20, 'بیجار', 'بیجار', '0');
INSERT INTO `cities` VALUES (721, 20, 'چناره', 'چناره', '0');
INSERT INTO `cities` VALUES (722, 20, 'دزج', 'دزج', '0');
INSERT INTO `cities` VALUES (723, 20, 'دلبران', 'دلبران', '0');
INSERT INTO `cities` VALUES (724, 20, 'دهگلان', 'دهگلان', '0');
INSERT INTO `cities` VALUES (725, 20, 'دیواندره', 'دیواندره', '0');
INSERT INTO `cities` VALUES (726, 20, 'زرینه', 'زرینه', '0');
INSERT INTO `cities` VALUES (727, 20, 'سروآباد', 'سروآباد', '0');
INSERT INTO `cities` VALUES (728, 20, 'سریش آباد', 'سریش-آباد', '0');
INSERT INTO `cities` VALUES (729, 20, 'سقز', 'سقز', '0');
INSERT INTO `cities` VALUES (730, 20, 'سنندج', 'سنندج', '0');
INSERT INTO `cities` VALUES (731, 20, 'شویشه', 'شویشه', '0');
INSERT INTO `cities` VALUES (732, 20, 'صاحب', 'صاحب', '0');
INSERT INTO `cities` VALUES (733, 20, 'قروه', 'قروه', '0');
INSERT INTO `cities` VALUES (734, 20, 'کامیاران', 'کامیاران', '0');
INSERT INTO `cities` VALUES (735, 20, 'کانی دینار', 'کانی-دینار', '0');
INSERT INTO `cities` VALUES (736, 20, 'کانی سور', 'کانی-سور', '0');
INSERT INTO `cities` VALUES (737, 20, 'مریوان', 'مریوان', '0');
INSERT INTO `cities` VALUES (738, 20, 'موچش', 'موچش', '0');
INSERT INTO `cities` VALUES (739, 20, 'یاسوکند', 'یاسوکند', '0');
INSERT INTO `cities` VALUES (740, 21, 'اختیارآباد', 'اختیارآباد', '0');
INSERT INTO `cities` VALUES (741, 21, 'ارزوئیه', 'ارزوئیه', '0');
INSERT INTO `cities` VALUES (742, 21, 'امین شهر', 'امین-شهر', '0');
INSERT INTO `cities` VALUES (743, 21, 'انار', 'انار', '0');
INSERT INTO `cities` VALUES (744, 21, 'اندوهجرد', 'اندوهجرد', '0');
INSERT INTO `cities` VALUES (745, 21, 'باغین', 'باغین', '0');
INSERT INTO `cities` VALUES (746, 21, 'بافت', 'بافت', '0');
INSERT INTO `cities` VALUES (747, 21, 'بردسیر', 'بردسیر', '0');
INSERT INTO `cities` VALUES (748, 21, 'بروات', 'بروات', '0');
INSERT INTO `cities` VALUES (749, 21, 'بزنجان', 'بزنجان', '0');
INSERT INTO `cities` VALUES (750, 21, 'بم', 'بم', '0');
INSERT INTO `cities` VALUES (751, 21, 'بهرمان', 'بهرمان', '0');
INSERT INTO `cities` VALUES (752, 21, 'پاریز', 'پاریز', '0');
INSERT INTO `cities` VALUES (753, 21, 'جبالبارز', 'جبالبارز', '0');
INSERT INTO `cities` VALUES (754, 21, 'جوپار', 'جوپار', '0');
INSERT INTO `cities` VALUES (755, 21, 'جوزم', 'جوزم', '0');
INSERT INTO `cities` VALUES (756, 21, 'جیرفت', 'جیرفت', '0');
INSERT INTO `cities` VALUES (757, 21, 'چترود', 'چترود', '0');
INSERT INTO `cities` VALUES (758, 21, 'خاتون آباد', 'خاتون-آباد', '0');
INSERT INTO `cities` VALUES (759, 21, 'خانوک', 'خانوک', '0');
INSERT INTO `cities` VALUES (760, 21, 'خورسند', 'خورسند', '0');
INSERT INTO `cities` VALUES (761, 21, 'درب بهشت', 'درب-بهشت', '0');
INSERT INTO `cities` VALUES (762, 21, 'دهج', 'دهج', '0');
INSERT INTO `cities` VALUES (763, 21, 'رابر', 'رابر', '0');
INSERT INTO `cities` VALUES (764, 21, 'راور', 'راور', '0');
INSERT INTO `cities` VALUES (765, 21, 'راین', 'راین', '0');
INSERT INTO `cities` VALUES (766, 21, 'رفسنجان', 'رفسنجان', '0');
INSERT INTO `cities` VALUES (767, 21, 'رودبار', 'کرمان-رودبار', '0');
INSERT INTO `cities` VALUES (768, 21, 'ریحان شهر', 'ریحان-شهر', '0');
INSERT INTO `cities` VALUES (769, 21, 'زرند', 'زرند', '0');
INSERT INTO `cities` VALUES (770, 21, 'زنگی آباد', 'زنگی-آباد', '0');
INSERT INTO `cities` VALUES (771, 21, 'زیدآباد', 'زیدآباد', '0');
INSERT INTO `cities` VALUES (772, 21, 'سیرجان', 'سیرجان', '0');
INSERT INTO `cities` VALUES (773, 21, 'شهداد', 'شهداد', '0');
INSERT INTO `cities` VALUES (774, 21, 'شهربابک', 'شهربابک', '0');
INSERT INTO `cities` VALUES (775, 21, 'صفائیه', 'صفائیه', '0');
INSERT INTO `cities` VALUES (776, 21, 'عنبرآباد', 'عنبرآباد', '0');
INSERT INTO `cities` VALUES (777, 21, 'فاریاب', 'فاریاب', '0');
INSERT INTO `cities` VALUES (778, 21, 'فهرج', 'فهرج', '0');
INSERT INTO `cities` VALUES (779, 21, 'قلعه گنج', 'قلعه-گنج', '0');
INSERT INTO `cities` VALUES (780, 21, 'کاظم آباد', 'کاظم-آباد', '0');
INSERT INTO `cities` VALUES (781, 21, 'کرمان', 'شهر-کرمان', '0');
INSERT INTO `cities` VALUES (782, 21, 'کشکوئیه', 'کشکوئیه', '0');
INSERT INTO `cities` VALUES (783, 21, 'کهنوج', 'کهنوج', '0');
INSERT INTO `cities` VALUES (784, 21, 'کوهبنان', 'کوهبنان', '0');
INSERT INTO `cities` VALUES (785, 21, 'کیانشهر', 'کیانشهر', '0');
INSERT INTO `cities` VALUES (786, 21, 'گلباف', 'گلباف', '0');
INSERT INTO `cities` VALUES (787, 21, 'گلزار', 'گلزار', '0');
INSERT INTO `cities` VALUES (788, 21, 'لاله زار', 'لاله-زار', '0');
INSERT INTO `cities` VALUES (789, 21, 'ماهان', 'ماهان', '0');
INSERT INTO `cities` VALUES (790, 21, 'محمدآباد', 'کرمان-محمدآباد', '0');
INSERT INTO `cities` VALUES (791, 21, 'محی آباد', 'محی-آباد', '0');
INSERT INTO `cities` VALUES (792, 21, 'مردهک', 'مردهک', '0');
INSERT INTO `cities` VALUES (793, 21, 'مس سرچشمه', 'مس-سرچشمه', '0');
INSERT INTO `cities` VALUES (794, 21, 'منوجان', 'منوجان', '0');
INSERT INTO `cities` VALUES (795, 21, 'نجف شهر', 'نجف-شهر', '0');
INSERT INTO `cities` VALUES (796, 21, 'نرماشیر', 'نرماشیر', '0');
INSERT INTO `cities` VALUES (797, 21, 'نظام شهر', 'نظام-شهر', '0');
INSERT INTO `cities` VALUES (798, 21, 'نگار', 'نگار', '0');
INSERT INTO `cities` VALUES (799, 21, 'نودژ', 'نودژ', '0');
INSERT INTO `cities` VALUES (800, 21, 'هجدک', 'هجدک', '0');
INSERT INTO `cities` VALUES (801, 21, 'یزدان شهر', 'یزدان-شهر', '0');
INSERT INTO `cities` VALUES (802, 22, 'ازگله', 'ازگله', '0');
INSERT INTO `cities` VALUES (803, 22, 'اسلام آباد غرب', 'اسلام-آباد-غرب', '0');
INSERT INTO `cities` VALUES (804, 22, 'باینگان', 'باینگان', '0');
INSERT INTO `cities` VALUES (805, 22, 'بیستون', 'بیستون', '0');
INSERT INTO `cities` VALUES (806, 22, 'پاوه', 'پاوه', '0');
INSERT INTO `cities` VALUES (807, 22, 'تازه آباد', 'تازه-آباد', '0');
INSERT INTO `cities` VALUES (808, 22, 'جوان رود', 'جوان-رود', '0');
INSERT INTO `cities` VALUES (809, 22, 'حمیل', 'حمیل', '0');
INSERT INTO `cities` VALUES (810, 22, 'ماهیدشت', 'ماهیدشت', '0');
INSERT INTO `cities` VALUES (811, 22, 'روانسر', 'روانسر', '0');
INSERT INTO `cities` VALUES (812, 22, 'سرپل ذهاب', 'سرپل-ذهاب', '0');
INSERT INTO `cities` VALUES (813, 22, 'سرمست', 'سرمست', '0');
INSERT INTO `cities` VALUES (814, 22, 'سطر', 'سطر', '0');
INSERT INTO `cities` VALUES (815, 22, 'سنقر', 'سنقر', '0');
INSERT INTO `cities` VALUES (816, 22, 'سومار', 'سومار', '0');
INSERT INTO `cities` VALUES (817, 22, 'شاهو', 'شاهو', '0');
INSERT INTO `cities` VALUES (818, 22, 'صحنه', 'صحنه', '0');
INSERT INTO `cities` VALUES (819, 22, 'قصرشیرین', 'قصرشیرین', '0');
INSERT INTO `cities` VALUES (820, 22, 'کرمانشاه', 'شهر-کرمانشاه', '0');
INSERT INTO `cities` VALUES (821, 22, 'کرندغرب', 'کرندغرب', '0');
INSERT INTO `cities` VALUES (822, 22, 'کنگاور', 'کنگاور', '0');
INSERT INTO `cities` VALUES (823, 22, 'کوزران', 'کوزران', '0');
INSERT INTO `cities` VALUES (824, 22, 'گهواره', 'گهواره', '0');
INSERT INTO `cities` VALUES (825, 22, 'گیلانغرب', 'گیلانغرب', '0');
INSERT INTO `cities` VALUES (826, 22, 'میان راهان', 'میان-راهان', '0');
INSERT INTO `cities` VALUES (827, 22, 'نودشه', 'نودشه', '0');
INSERT INTO `cities` VALUES (828, 22, 'نوسود', 'نوسود', '0');
INSERT INTO `cities` VALUES (829, 22, 'هرسین', 'هرسین', '0');
INSERT INTO `cities` VALUES (830, 22, 'هلشی', 'هلشی', '0');
INSERT INTO `cities` VALUES (831, 23, 'باشت', 'باشت', '0');
INSERT INTO `cities` VALUES (832, 23, 'پاتاوه', 'پاتاوه', '0');
INSERT INTO `cities` VALUES (833, 23, 'چرام', 'چرام', '0');
INSERT INTO `cities` VALUES (834, 23, 'چیتاب', 'چیتاب', '0');
INSERT INTO `cities` VALUES (835, 23, 'دهدشت', 'دهدشت', '0');
INSERT INTO `cities` VALUES (836, 23, 'دوگنبدان', 'دوگنبدان', '0');
INSERT INTO `cities` VALUES (837, 23, 'دیشموک', 'دیشموک', '0');
INSERT INTO `cities` VALUES (838, 23, 'سوق', 'سوق', '0');
INSERT INTO `cities` VALUES (839, 23, 'سی سخت', 'سی-سخت', '0');
INSERT INTO `cities` VALUES (840, 23, 'قلعه رئیسی', 'قلعه-رئیسی', '0');
INSERT INTO `cities` VALUES (841, 23, 'گراب سفلی', 'گراب-سفلی', '0');
INSERT INTO `cities` VALUES (842, 23, 'لنده', 'لنده', '0');
INSERT INTO `cities` VALUES (843, 23, 'لیکک', 'لیکک', '0');
INSERT INTO `cities` VALUES (844, 23, 'مادوان', 'مادوان', '0');
INSERT INTO `cities` VALUES (845, 23, 'مارگون', 'مارگون', '0');
INSERT INTO `cities` VALUES (846, 23, 'یاسوج', 'یاسوج', '0');
INSERT INTO `cities` VALUES (847, 24, 'انبارآلوم', 'انبارآلوم', '0');
INSERT INTO `cities` VALUES (848, 24, 'اینچه برون', 'اینچه-برون', '0');
INSERT INTO `cities` VALUES (849, 24, 'آزادشهر', 'آزادشهر', '0');
INSERT INTO `cities` VALUES (850, 24, 'آق قلا', 'آق-قلا', '0');
INSERT INTO `cities` VALUES (851, 24, 'بندرترکمن', 'بندرترکمن', '0');
INSERT INTO `cities` VALUES (852, 24, 'بندرگز', 'بندرگز', '0');
INSERT INTO `cities` VALUES (853, 24, 'جلین', 'جلین', '0');
INSERT INTO `cities` VALUES (854, 24, 'خان ببین', 'خان-ببین', '0');
INSERT INTO `cities` VALUES (855, 24, 'دلند', 'دلند', '0');
INSERT INTO `cities` VALUES (856, 24, 'رامیان', 'رامیان', '0');
INSERT INTO `cities` VALUES (857, 24, 'سرخنکلاته', 'سرخنکلاته', '0');
INSERT INTO `cities` VALUES (858, 24, 'سیمین شهر', 'سیمین-شهر', '0');
INSERT INTO `cities` VALUES (859, 24, 'علی آباد کتول', 'علی-آباد-کتول', '0');
INSERT INTO `cities` VALUES (860, 24, 'فاضل آباد', 'فاضل-آباد', '0');
INSERT INTO `cities` VALUES (861, 24, 'کردکوی', 'کردکوی', '0');
INSERT INTO `cities` VALUES (862, 24, 'کلاله', 'کلاله', '0');
INSERT INTO `cities` VALUES (863, 24, 'گالیکش', 'گالیکش', '0');
INSERT INTO `cities` VALUES (864, 24, 'گرگان', 'گرگان', '0');
INSERT INTO `cities` VALUES (865, 24, 'گمیش تپه', 'گمیش-تپه', '0');
INSERT INTO `cities` VALUES (866, 24, 'گنبدکاووس', 'گنبدکاووس', '0');
INSERT INTO `cities` VALUES (867, 24, 'مراوه', 'مراوه', '0');
INSERT INTO `cities` VALUES (868, 24, 'مینودشت', 'مینودشت', '0');
INSERT INTO `cities` VALUES (869, 24, 'نگین شهر', 'نگین-شهر', '0');
INSERT INTO `cities` VALUES (870, 24, 'نوده خاندوز', 'نوده-خاندوز', '0');
INSERT INTO `cities` VALUES (871, 24, 'نوکنده', 'نوکنده', '0');
INSERT INTO `cities` VALUES (872, 25, 'ازنا', 'ازنا', '0');
INSERT INTO `cities` VALUES (873, 25, 'اشترینان', 'اشترینان', '0');
INSERT INTO `cities` VALUES (874, 25, 'الشتر', 'الشتر', '0');
INSERT INTO `cities` VALUES (875, 25, 'الیگودرز', 'الیگودرز', '0');
INSERT INTO `cities` VALUES (876, 25, 'بروجرد', 'بروجرد', '0');
INSERT INTO `cities` VALUES (877, 25, 'پلدختر', 'پلدختر', '0');
INSERT INTO `cities` VALUES (878, 25, 'چالانچولان', 'چالانچولان', '0');
INSERT INTO `cities` VALUES (879, 25, 'چغلوندی', 'چغلوندی', '0');
INSERT INTO `cities` VALUES (880, 25, 'چقابل', 'چقابل', '0');
INSERT INTO `cities` VALUES (881, 25, 'خرم آباد', 'لرستان-خرم-آباد', '0');
INSERT INTO `cities` VALUES (882, 25, 'درب گنبد', 'درب-گنبد', '0');
INSERT INTO `cities` VALUES (883, 25, 'دورود', 'دورود', '0');
INSERT INTO `cities` VALUES (884, 25, 'زاغه', 'زاغه', '0');
INSERT INTO `cities` VALUES (885, 25, 'سپیددشت', 'سپیددشت', '0');
INSERT INTO `cities` VALUES (886, 25, 'سراب دوره', 'سراب-دوره', '0');
INSERT INTO `cities` VALUES (887, 25, 'فیروزآباد', 'لرستان-فیروزآباد', '0');
INSERT INTO `cities` VALUES (888, 25, 'کونانی', 'کونانی', '0');
INSERT INTO `cities` VALUES (889, 25, 'کوهدشت', 'کوهدشت', '0');
INSERT INTO `cities` VALUES (890, 25, 'گراب', 'گراب', '0');
INSERT INTO `cities` VALUES (891, 25, 'معمولان', 'معمولان', '0');
INSERT INTO `cities` VALUES (892, 25, 'مومن آباد', 'مومن-آباد', '0');
INSERT INTO `cities` VALUES (893, 25, 'نورآباد', 'لرستان-نورآباد', '0');
INSERT INTO `cities` VALUES (894, 25, 'ویسیان', 'ویسیان', '0');
INSERT INTO `cities` VALUES (895, 26, 'احمدسرگوراب', 'احمدسرگوراب', '0');
INSERT INTO `cities` VALUES (896, 26, 'اسالم', 'اسالم', '0');
INSERT INTO `cities` VALUES (897, 26, 'اطاقور', 'اطاقور', '0');
INSERT INTO `cities` VALUES (898, 26, 'املش', 'املش', '0');
INSERT INTO `cities` VALUES (899, 26, 'آستارا', 'آستارا', '0');
INSERT INTO `cities` VALUES (900, 26, 'آستانه اشرفیه', 'آستانه-اشرفیه', '0');
INSERT INTO `cities` VALUES (901, 26, 'بازار جمعه', 'بازار-جمعه', '0');
INSERT INTO `cities` VALUES (902, 26, 'بره سر', 'بره-سر', '0');
INSERT INTO `cities` VALUES (903, 26, 'بندرانزلی', 'بندرانزلی', '0');
INSERT INTO `cities` VALUES (906, 26, 'پره سر', 'پره-سر', '0');
INSERT INTO `cities` VALUES (907, 26, 'تالش', 'تالش', '0');
INSERT INTO `cities` VALUES (908, 26, 'توتکابن', 'توتکابن', '0');
INSERT INTO `cities` VALUES (909, 26, 'جیرنده', 'جیرنده', '0');
INSERT INTO `cities` VALUES (910, 26, 'چابکسر', 'چابکسر', '0');
INSERT INTO `cities` VALUES (911, 26, 'چاف و چمخاله', 'چاف-و-چمخاله', '0');
INSERT INTO `cities` VALUES (912, 26, 'چوبر', 'چوبر', '0');
INSERT INTO `cities` VALUES (913, 26, 'حویق', 'حویق', '0');
INSERT INTO `cities` VALUES (914, 26, 'خشکبیجار', 'خشکبیجار', '0');
INSERT INTO `cities` VALUES (915, 26, 'خمام', 'خمام', '0');
INSERT INTO `cities` VALUES (916, 26, 'دیلمان', 'دیلمان', '0');
INSERT INTO `cities` VALUES (917, 26, 'رانکوه', 'رانکوه', '0');
INSERT INTO `cities` VALUES (918, 26, 'رحیم آباد', 'رحیم-آباد', '0');
INSERT INTO `cities` VALUES (919, 26, 'رستم آباد', 'رستم-آباد', '0');
INSERT INTO `cities` VALUES (920, 26, 'رشت', 'رشت', '0');
INSERT INTO `cities` VALUES (921, 26, 'رضوانشهر', 'گیلان-رضوانشهر', '0');
INSERT INTO `cities` VALUES (922, 26, 'رودبار', 'گیلان-رودبار', '0');
INSERT INTO `cities` VALUES (923, 26, 'رودبنه', 'رودبنه', '0');
INSERT INTO `cities` VALUES (924, 26, 'رودسر', 'رودسر', '0');
INSERT INTO `cities` VALUES (925, 26, 'سنگر', 'سنگر', '0');
INSERT INTO `cities` VALUES (926, 26, 'سیاهکل', 'سیاهکل', '0');
INSERT INTO `cities` VALUES (927, 26, 'شفت', 'شفت', '0');
INSERT INTO `cities` VALUES (928, 26, 'شلمان', 'شلمان', '0');
INSERT INTO `cities` VALUES (929, 26, 'صومعه سرا', 'صومعه-سرا', '0');
INSERT INTO `cities` VALUES (930, 26, 'فومن', 'فومن', '0');
INSERT INTO `cities` VALUES (931, 26, 'کلاچای', 'کلاچای', '0');
INSERT INTO `cities` VALUES (932, 26, 'کوچصفهان', 'کوچصفهان', '0');
INSERT INTO `cities` VALUES (933, 26, 'کومله', 'کومله', '0');
INSERT INTO `cities` VALUES (934, 26, 'کیاشهر', 'کیاشهر', '0');
INSERT INTO `cities` VALUES (935, 26, 'گوراب زرمیخ', 'گوراب-زرمیخ', '0');
INSERT INTO `cities` VALUES (936, 26, 'لاهیجان', 'لاهیجان', '0');
INSERT INTO `cities` VALUES (937, 26, 'لشت نشا', 'لشت-نشا', '0');
INSERT INTO `cities` VALUES (938, 26, 'لنگرود', 'لنگرود', '0');
INSERT INTO `cities` VALUES (939, 26, 'لوشان', 'لوشان', '0');
INSERT INTO `cities` VALUES (940, 26, 'لولمان', 'لولمان', '0');
INSERT INTO `cities` VALUES (941, 26, 'لوندویل', 'لوندویل', '0');
INSERT INTO `cities` VALUES (942, 26, 'لیسار', 'لیسار', '0');
INSERT INTO `cities` VALUES (943, 26, 'ماسال', 'ماسال', '0');
INSERT INTO `cities` VALUES (944, 26, 'ماسوله', 'ماسوله', '0');
INSERT INTO `cities` VALUES (945, 26, 'مرجقل', 'مرجقل', '0');
INSERT INTO `cities` VALUES (946, 26, 'منجیل', 'منجیل', '0');
INSERT INTO `cities` VALUES (947, 26, 'واجارگاه', 'واجارگاه', '0');
INSERT INTO `cities` VALUES (948, 27, 'امیرکلا', 'امیرکلا', '0');
INSERT INTO `cities` VALUES (949, 27, 'ایزدشهر', 'ایزدشهر', '0');
INSERT INTO `cities` VALUES (950, 27, 'آلاشت', 'آلاشت', '0');
INSERT INTO `cities` VALUES (951, 27, 'آمل', 'آمل', '0');
INSERT INTO `cities` VALUES (952, 27, 'بابل', 'بابل', '0');
INSERT INTO `cities` VALUES (953, 27, 'بابلسر', 'بابلسر', '0');
INSERT INTO `cities` VALUES (954, 27, 'بالاده', 'مازندران-بالاده', '0');
INSERT INTO `cities` VALUES (955, 27, 'بهشهر', 'بهشهر', '0');
INSERT INTO `cities` VALUES (956, 27, 'بهنمیر', 'بهنمیر', '0');
INSERT INTO `cities` VALUES (957, 27, 'پل سفید', 'پل-سفید', '0');
INSERT INTO `cities` VALUES (958, 27, 'تنکابن', 'تنکابن', '0');
INSERT INTO `cities` VALUES (959, 27, 'جویبار', 'جویبار', '0');
INSERT INTO `cities` VALUES (960, 27, 'چالوس', 'چالوس', '0');
INSERT INTO `cities` VALUES (961, 27, 'چمستان', 'چمستان', '0');
INSERT INTO `cities` VALUES (962, 27, 'خرم آباد', 'مازندران-خرم-آباد', '0');
INSERT INTO `cities` VALUES (963, 27, 'خلیل شهر', 'خلیل-شهر', '0');
INSERT INTO `cities` VALUES (964, 27, 'خوش رودپی', 'خوش-رودپی', '0');
INSERT INTO `cities` VALUES (965, 27, 'دابودشت', 'دابودشت', '0');
INSERT INTO `cities` VALUES (966, 27, 'رامسر', 'رامسر', '0');
INSERT INTO `cities` VALUES (967, 27, 'رستمکلا', 'رستمکلا', '0');
INSERT INTO `cities` VALUES (968, 27, 'رویان', 'رویان', '0');
INSERT INTO `cities` VALUES (969, 27, 'رینه', 'رینه', '0');
INSERT INTO `cities` VALUES (970, 27, 'زرگرمحله', 'زرگرمحله', '0');
INSERT INTO `cities` VALUES (971, 27, 'زیرآب', 'زیرآب', '0');
INSERT INTO `cities` VALUES (972, 27, 'ساری', 'ساری', '0');
INSERT INTO `cities` VALUES (973, 27, 'سرخرود', 'سرخرود', '0');
INSERT INTO `cities` VALUES (974, 27, 'سلمان شهر', 'سلمان-شهر', '0');
INSERT INTO `cities` VALUES (975, 27, 'سورک', 'سورک', '0');
INSERT INTO `cities` VALUES (976, 27, 'شیرگاه', 'شیرگاه', '0');
INSERT INTO `cities` VALUES (977, 27, 'شیرود', 'شیرود', '0');
INSERT INTO `cities` VALUES (978, 27, 'عباس آباد', 'عباس-آباد', '0');
INSERT INTO `cities` VALUES (979, 27, 'فریدونکنار', 'فریدونکنار', '0');
INSERT INTO `cities` VALUES (980, 27, 'فریم', 'فریم', '0');
INSERT INTO `cities` VALUES (981, 27, 'قائم شهر', 'قائم-شهر', '0');
INSERT INTO `cities` VALUES (982, 27, 'کتالم', 'کتالم', '0');
INSERT INTO `cities` VALUES (983, 27, 'کلارآباد', 'کلارآباد', '0');
INSERT INTO `cities` VALUES (984, 27, 'کلاردشت', 'کلاردشت', '0');
INSERT INTO `cities` VALUES (985, 27, 'کله بست', 'کله-بست', '0');
INSERT INTO `cities` VALUES (986, 27, 'کوهی خیل', 'کوهی-خیل', '0');
INSERT INTO `cities` VALUES (987, 27, 'کیاسر', 'کیاسر', '0');
INSERT INTO `cities` VALUES (988, 27, 'کیاکلا', 'کیاکلا', '0');
INSERT INTO `cities` VALUES (989, 27, 'گتاب', 'گتاب', '0');
INSERT INTO `cities` VALUES (990, 27, 'گزنک', 'گزنک', '0');
INSERT INTO `cities` VALUES (991, 27, 'گلوگاه', 'گلوگاه', '0');
INSERT INTO `cities` VALUES (992, 27, 'محمودآباد', 'مازندران-محمودآباد', '0');
INSERT INTO `cities` VALUES (993, 27, 'مرزن آباد', 'مرزن-آباد', '0');
INSERT INTO `cities` VALUES (994, 27, 'مرزیکلا', 'مرزیکلا', '0');
INSERT INTO `cities` VALUES (995, 27, 'نشتارود', 'نشتارود', '0');
INSERT INTO `cities` VALUES (996, 27, 'نکا', 'نکا', '0');
INSERT INTO `cities` VALUES (997, 27, 'نور', 'نور', '0');
INSERT INTO `cities` VALUES (998, 27, 'نوشهر', 'نوشهر', '0');
INSERT INTO `cities` VALUES (999, 28, 'اراک', 'اراک', '0');
INSERT INTO `cities` VALUES (1000, 28, 'آستانه', 'آستانه', '0');
INSERT INTO `cities` VALUES (1001, 28, 'آشتیان', 'آشتیان', '0');
INSERT INTO `cities` VALUES (1002, 28, 'پرندک', 'پرندک', '0');
INSERT INTO `cities` VALUES (1003, 28, 'تفرش', 'تفرش', '0');
INSERT INTO `cities` VALUES (1004, 28, 'توره', 'توره', '0');
INSERT INTO `cities` VALUES (1005, 28, 'جاورسیان', 'جاورسیان', '0');
INSERT INTO `cities` VALUES (1006, 28, 'خشکرود', 'خشکرود', '0');
INSERT INTO `cities` VALUES (1007, 28, 'خمین', 'خمین', '0');
INSERT INTO `cities` VALUES (1008, 28, 'خنداب', 'خنداب', '0');
INSERT INTO `cities` VALUES (1009, 28, 'داودآباد', 'داودآباد', '0');
INSERT INTO `cities` VALUES (1010, 28, 'دلیجان', 'دلیجان', '0');
INSERT INTO `cities` VALUES (1011, 28, 'رازقان', 'رازقان', '0');
INSERT INTO `cities` VALUES (1012, 28, 'زاویه', 'زاویه', '0');
INSERT INTO `cities` VALUES (1013, 28, 'ساروق', 'ساروق', '0');
INSERT INTO `cities` VALUES (1014, 28, 'ساوه', 'ساوه', '0');
INSERT INTO `cities` VALUES (1015, 28, 'سنجان', 'سنجان', '0');
INSERT INTO `cities` VALUES (1016, 28, 'شازند', 'شازند', '0');
INSERT INTO `cities` VALUES (1017, 28, 'غرق آباد', 'غرق-آباد', '0');
INSERT INTO `cities` VALUES (1018, 28, 'فرمهین', 'فرمهین', '0');
INSERT INTO `cities` VALUES (1019, 28, 'قورچی باشی', 'قورچی-باشی', '0');
INSERT INTO `cities` VALUES (1020, 28, 'کرهرود', 'کرهرود', '0');
INSERT INTO `cities` VALUES (1021, 28, 'کمیجان', 'کمیجان', '0');
INSERT INTO `cities` VALUES (1022, 28, 'مامونیه', 'مامونیه', '0');
INSERT INTO `cities` VALUES (1023, 28, 'محلات', 'محلات', '0');
INSERT INTO `cities` VALUES (1024, 28, 'مهاجران', 'مهاجران', '0');
INSERT INTO `cities` VALUES (1025, 28, 'میلاجرد', 'میلاجرد', '0');
INSERT INTO `cities` VALUES (1026, 28, 'نراق', 'نراق', '0');
INSERT INTO `cities` VALUES (1027, 28, 'نوبران', 'نوبران', '0');
INSERT INTO `cities` VALUES (1028, 28, 'نیمور', 'نیمور', '0');
INSERT INTO `cities` VALUES (1029, 28, 'هندودر', 'هندودر', '0');
INSERT INTO `cities` VALUES (1030, 29, 'ابوموسی', 'ابوموسی', '0');
INSERT INTO `cities` VALUES (1031, 29, 'بستک', 'بستک', '0');
INSERT INTO `cities` VALUES (1032, 29, 'بندرجاسک', 'بندرجاسک', '0');
INSERT INTO `cities` VALUES (1033, 29, 'بندرچارک', 'بندرچارک', '0');
INSERT INTO `cities` VALUES (1034, 29, 'بندرخمیر', 'بندرخمیر', '0');
INSERT INTO `cities` VALUES (1035, 29, 'بندرعباس', 'بندرعباس', '0');
INSERT INTO `cities` VALUES (1036, 29, 'بندرلنگه', 'بندرلنگه', '0');
INSERT INTO `cities` VALUES (1037, 29, 'بیکا', 'بیکا', '0');
INSERT INTO `cities` VALUES (1038, 29, 'پارسیان', 'پارسیان', '0');
INSERT INTO `cities` VALUES (1039, 29, 'تخت', 'تخت', '0');
INSERT INTO `cities` VALUES (1040, 29, 'جناح', 'جناح', '0');
INSERT INTO `cities` VALUES (1041, 29, 'حاجی آباد', 'هرمزگان-حاجی-آباد', '0');
INSERT INTO `cities` VALUES (1042, 29, 'درگهان', 'درگهان', '0');
INSERT INTO `cities` VALUES (1043, 29, 'دهبارز', 'دهبارز', '0');
INSERT INTO `cities` VALUES (1044, 29, 'رویدر', 'رویدر', '0');
INSERT INTO `cities` VALUES (1045, 29, 'زیارتعلی', 'زیارتعلی', '0');
INSERT INTO `cities` VALUES (1046, 29, 'سردشت', 'هرمزگان-سردشت', '0');
INSERT INTO `cities` VALUES (1047, 29, 'سندرک', 'سندرک', '0');
INSERT INTO `cities` VALUES (1048, 29, 'سوزا', 'سوزا', '0');
INSERT INTO `cities` VALUES (1049, 29, 'سیریک', 'سیریک', '0');
INSERT INTO `cities` VALUES (1050, 29, 'فارغان', 'فارغان', '0');
INSERT INTO `cities` VALUES (1051, 29, 'فین', 'فین', '0');
INSERT INTO `cities` VALUES (1052, 29, 'قشم', 'قشم', '0');
INSERT INTO `cities` VALUES (1053, 29, 'قلعه قاضی', 'قلعه-قاضی', '0');
INSERT INTO `cities` VALUES (1054, 29, 'کنگ', 'کنگ', '0');
INSERT INTO `cities` VALUES (1055, 29, 'کوشکنار', 'کوشکنار', '0');
INSERT INTO `cities` VALUES (1056, 29, 'کیش', 'کیش', '0');
INSERT INTO `cities` VALUES (1057, 29, 'گوهران', 'گوهران', '0');
INSERT INTO `cities` VALUES (1058, 29, 'میناب', 'میناب', '0');
INSERT INTO `cities` VALUES (1059, 29, 'هرمز', 'هرمز', '0');
INSERT INTO `cities` VALUES (1060, 29, 'هشتبندی', 'هشتبندی', '0');
INSERT INTO `cities` VALUES (1061, 30, 'ازندریان', 'ازندریان', '0');
INSERT INTO `cities` VALUES (1062, 30, 'اسدآباد', 'اسدآباد', '0');
INSERT INTO `cities` VALUES (1063, 30, 'برزول', 'برزول', '0');
INSERT INTO `cities` VALUES (1064, 30, 'بهار', 'بهار', '0');
INSERT INTO `cities` VALUES (1065, 30, 'تویسرکان', 'تویسرکان', '0');
INSERT INTO `cities` VALUES (1066, 30, 'جورقان', 'جورقان', '0');
INSERT INTO `cities` VALUES (1067, 30, 'جوکار', 'جوکار', '0');
INSERT INTO `cities` VALUES (1068, 30, 'دمق', 'دمق', '0');
INSERT INTO `cities` VALUES (1069, 30, 'رزن', 'رزن', '0');
INSERT INTO `cities` VALUES (1070, 30, 'زنگنه', 'زنگنه', '0');
INSERT INTO `cities` VALUES (1071, 30, 'سامن', 'سامن', '0');
INSERT INTO `cities` VALUES (1072, 30, 'سرکان', 'سرکان', '0');
INSERT INTO `cities` VALUES (1073, 30, 'شیرین سو', 'شیرین-سو', '0');
INSERT INTO `cities` VALUES (1074, 30, 'صالح آباد', 'همدان-صالح-آباد', '0');
INSERT INTO `cities` VALUES (1075, 30, 'فامنین', 'فامنین', '0');
INSERT INTO `cities` VALUES (1076, 30, 'فرسفج', 'فرسفج', '0');
INSERT INTO `cities` VALUES (1077, 30, 'فیروزان', 'فیروزان', '0');
INSERT INTO `cities` VALUES (1078, 30, 'قروه درجزین', 'قروه-درجزین', '0');
INSERT INTO `cities` VALUES (1079, 30, 'قهاوند', 'قهاوند', '0');
INSERT INTO `cities` VALUES (1080, 30, 'کبودر آهنگ', 'کبودر-آهنگ', '0');
INSERT INTO `cities` VALUES (1081, 30, 'گل تپه', 'گل-تپه', '0');
INSERT INTO `cities` VALUES (1082, 30, 'گیان', 'گیان', '0');
INSERT INTO `cities` VALUES (1083, 30, 'لالجین', 'لالجین', '0');
INSERT INTO `cities` VALUES (1084, 30, 'مریانج', 'مریانج', '0');
INSERT INTO `cities` VALUES (1085, 30, 'ملایر', 'ملایر', '0');
INSERT INTO `cities` VALUES (1086, 30, 'نهاوند', 'نهاوند', '0');
INSERT INTO `cities` VALUES (1087, 30, 'همدان', 'شهر-همدان', '0');
INSERT INTO `cities` VALUES (1088, 31, 'ابرکوه', 'ابرکوه', '0');
INSERT INTO `cities` VALUES (1089, 31, 'احمدآباد', 'احمدآباد', '0');
INSERT INTO `cities` VALUES (1090, 31, 'اردکان', 'یزد-اردکان', '0');
INSERT INTO `cities` VALUES (1091, 31, 'اشکذر', 'اشکذر', '0');
INSERT INTO `cities` VALUES (1092, 31, 'بافق', 'بافق', '0');
INSERT INTO `cities` VALUES (1093, 31, 'بفروئیه', 'بفروئیه', '0');
INSERT INTO `cities` VALUES (1094, 31, 'بهاباد', 'بهاباد', '0');
INSERT INTO `cities` VALUES (1095, 31, 'تفت', 'تفت', '0');
INSERT INTO `cities` VALUES (1096, 31, 'حمیدیا', 'حمیدیا', '0');
INSERT INTO `cities` VALUES (1097, 31, 'خضرآباد', 'خضرآباد', '0');
INSERT INTO `cities` VALUES (1098, 31, 'دیهوک', 'دیهوک', '0');
INSERT INTO `cities` VALUES (1099, 31, 'زارچ', 'زارچ', '0');
INSERT INTO `cities` VALUES (1100, 31, 'شاهدیه', 'شاهدیه', '0');
INSERT INTO `cities` VALUES (1101, 31, 'طبس', 'یزد-طبس', '0');
INSERT INTO `cities` VALUES (1103, 31, 'عقدا', 'عقدا', '0');
INSERT INTO `cities` VALUES (1104, 31, 'مروست', 'مروست', '0');
INSERT INTO `cities` VALUES (1105, 31, 'مهردشت', 'مهردشت', '0');
INSERT INTO `cities` VALUES (1106, 31, 'مهریز', 'مهریز', '0');
INSERT INTO `cities` VALUES (1107, 31, 'میبد', 'میبد', '0');
INSERT INTO `cities` VALUES (1108, 31, 'ندوشن', 'ندوشن', '0');
INSERT INTO `cities` VALUES (1109, 31, 'نیر', 'یزد-نیر', '0');
INSERT INTO `cities` VALUES (1110, 31, 'هرات', 'هرات', '0');
INSERT INTO `cities` VALUES (1111, 31, 'یزد', 'شهر-یزد', '0');
INSERT INTO `cities` VALUES (1116, 8, 'پرند', 'پرند', '0');
INSERT INTO `cities` VALUES (1117, 5, 'فردیس', 'فردیس', '0');
INSERT INTO `cities` VALUES (1118, 5, 'مارلیک', 'مارلیک', '0');
INSERT INTO `cities` VALUES (1119, 27, 'سادات شهر', 'سادات-شهر', '0');

SET FOREIGN_KEY_CHECKS = 1;
